Push notification
evotor/integration-library pull request #104
Opened 2017-10-13 12:15 UTC by HeyAlex

add push notification

2017-11-24 12:03 UTC, notxcain requested changes

2017-11-24 12:03 UTC, notxcain commented on app/src/main/java/ru/evotor/integrations/PushNotificationReceiver.java
> +     * Получение индентификатора, нужный для посылки пушей
`Получение идентификатора, необходимого для отправки push-уведомлений`

2017-11-24 12:03 UTC, notxcain commented on app/src/main/java/ru/evotor/integrations/PushNotificationReceiver.java
> +    public abstract void onReceiveCorrelationID(Context context, String correlationID);
`onReceiveCorrelationId`

2017-11-24 12:03 UTC, notxcain commented on app/src/main/java/ru/evotor/integrations/PushNotificationReceiver.java
> +    public abstract void onReceiveCorrelationID(Context context, String correlationID);
`String correlationId`

2017-11-24 12:03 UTC, notxcain commented on app/src/main/java/ru/evotor/integrations/PushNotificationReceiver.java
> +    public void onReceive(Context context, Intent intent) {
`final` ?

2017-11-24 12:03 UTC, notxcain commented on app/src/main/java/ru/evotor/integrations/PushNotificationReceiver.java
> +     * После регистрации, вызовится {@link PushNotificationReceiver#onReceiveCorrelationID(Context, String)}
`onReceiveCorrelationId`

2017-11-24 13:39 UTC, notxcain requested changes

2017-11-24 13:39 UTC, notxcain commented on app/src/main/java/ru/evotor/integrations/PushNotificationReceiver.java
> +     * Обработка пуш уведомления
Давай везде поправим на существительное `push-уведомление`?

2017-11-27 11:45 UTC, xcam commented on app/src/main/java/ru/evotor/integrations/PushNotificationReceiver.java
> + * можно получить индентификтор устройства, который уже используется сервером, для рассылки пуш уведомлений.
опечатка

2017-11-27 11:45 UTC, xcam commented on app/src/main/java/ru/evotor/integrations/PushNotificationReceiver.java
> +package ru.evotor.integrations;
kotlin

2017-11-27 11:47 UTC, xcam commented on app/src/main/java/ru/evotor/integrations/PushNotificationReceiver.java
> +    public static void registerAppToReceiveNotifications(Context context) {
notnull

2017-11-27 11:48 UTC, xcam commented on app/src/main/java/ru/evotor/integrations/PushNotificationReceiver.java
> +        context.sendBroadcast(intent);
check permissions

2017-11-27 11:53 UTC, xcam requested changes
см замечания

2017-11-28 15:21 UTC, notxcain commented on app/src/main/java/ru/evotor/integrations/PushNotificationReceiver.java
> +    public abstract void onReceiveCorrelationId(Context context, String correlationId);
В `iOS SDK` есть callback который говорит об ошибке при регистрации в пуш сервисе. Не знаю насколько это важно тут и есть ли возможность отловить такое.

2017-12-19 19:52 UTC, madsunrise commented on app/src/main/java/ru/evotor/integrations/PushNotificationReceiver.java
> +    public void onReceive(Context context, Intent intent) {
А в чем проблема final, чисто из-за любопытства?

2018-01-18 14:42 UTC, xcam submitted a review, later dismissed

2018-05-04 09:23 UTC, xcam approved these changes

2018-05-04 09:26 UTC, notxcain approved these changes
🚀

2018-05-04 09:26 UTC, merged