1008
evotor/integration-library pull request #138
Opened 2018-04-09 08:09 UTC by Affordall

Attributes

2018-04-12 12:31 UTC, xcam commented on src/main/java/ru/evotor/framework/core/IntegrationManagerImpl.java
> +            } catch (RemoteException e) {
это откуда?

2018-04-12 12:32 UTC, xcam commented on src/main/java/ru/evotor/framework/core/action/datamapper/PositionMapper.java
> +                (Map<String, DomainAttributeValue>) bundle.getSerializable(KEY_ATTRIBUTES);
использование Serializable приведет к проблемам, когда у тебя добавятся\изменятся поля в сущности
 Поэтому используй bundle

2018-04-12 12:33 UTC, xcam commented on src/main/java/ru/evotor/framework/domain/DomainAttribute.kt
> +data class DomainAttribute(
почему Domain?

2018-04-12 12:34 UTC, xcam commented on src/main/java/ru/evotor/framework/domain/DomainAttribute.kt
> +        var attributeValuesForAdapter: List<DomainAttributeValue>? = null
ForAdapter тут почему?

2018-04-12 12:35 UTC, xcam commented on src/main/java/ru/evotor/framework/domain/DomainAttributeValue.kt
> +        val dictionaryUuid: String? = null,
почему не attributeUuid?

2018-04-12 12:35 UTC, xcam commented on src/main/java/ru/evotor/framework/domain/DomainAttributeValue.kt
> +        val dictionaryName: String? = null,
почем не attributeName?

2018-04-12 12:36 UTC, xcam commented on src/main/java/ru/evotor/framework/domain/DomainAttributeValue.kt
> +        val dictionaryName: String? = null,
почему мы вообще дублируем это поле?

2018-04-12 12:36 UTC, xcam commented on src/main/java/ru/evotor/framework/domain/DomainAttribute.kt
> +        val uuid: String? = null,
в каком случае у аттрибута это поле будет null?

2018-04-12 12:36 UTC, xcam commented on src/main/java/ru/evotor/framework/domain/DomainAttribute.kt
> +        val name: String? = null,
в каком случае у аттрибута это поле будет null?

2018-04-12 12:37 UTC, xcam commented on src/main/java/ru/evotor/framework/domain/DomainAttributeValue.kt
> +        val dictionaryUuid: String? = null,
в каком случае у аттрибута это поле будет null?

2018-04-12 12:37 UTC, xcam commented on src/main/java/ru/evotor/framework/domain/DomainAttributeValue.kt
> +        val dictionaryName: String? = null,
в каком случае у аттрибута это поле будет null?

2018-04-12 12:37 UTC, xcam commented on src/main/java/ru/evotor/framework/domain/DomainAttributeValue.kt
> +        val uuid: String? = null,
в каком случае у аттрибута это поле будет null?

2018-04-12 12:37 UTC, xcam commented on src/main/java/ru/evotor/framework/domain/DomainAttributeValue.kt
> +        val name: String? = null
в каком случае у аттрибута это поле будет null?

2018-04-12 12:37 UTC, xcam commented on src/main/java/ru/evotor/framework/domain/DomainAttributeValue.kt
> +data class DomainAttributeValue(
почему Domain?

2018-04-12 12:38 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/Position.java
> +     * Атрибуты
что является ключом, а что значением? Нужно описание

2018-04-12 12:39 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/Position.java
> -            TaxNumber taxNumber,
это почему?

2018-04-12 12:41 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/Position.java
> +            @Nullable Map<String, DomainAttributeValue> attributes
кажется мы нарушили совместимость с предыдущими версиями.

2018-04-12 12:41 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/Position.java
> +    public Map<String, DomainAttributeValue> getAttributes() {
нет аннотации Nullable

2018-04-12 12:41 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/Position.java
> +    public void setAttributes(Map<String, DomainAttributeValue> attributes) {
нет аннотации Nullable

2018-04-12 12:43 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/Position.java
> +        dest.writeTypedList(this.subPositions);
пора добавлять версионность Parcelable, так как иначе получим ошибки поддержки предыдущих версий

2018-04-12 12:43 UTC, xcam requested changes
Нужны исправления

2018-04-18 10:54 UTC, epanina commented on src/main/java/ru/evotor/framework/core/action/datamapper/PositionMapper.java
> +                (Map<String, DomainAttributeValue>) bundle.getSerializable(KEY_ATTRIBUTES);
Не понимаю коммент объясни пожалуйста подробнее.

2018-04-18 11:38 UTC, Affordall commented on src/main/java/ru/evotor/framework/core/IntegrationManagerImpl.java
> +            } catch (RemoteException e) {
Это должны были поправить еще в задаче про "exception вместе со сторонней интеграцией".

2018-04-18 11:43 UTC, Affordall commented on src/main/java/ru/evotor/framework/domain/DomainAttributeValue.kt
> +        val dictionaryUuid: String? = null,
потому что здесь мы храним dictionaryUuid, а не attributeUuid

2018-04-18 11:43 UTC, Affordall commented on src/main/java/ru/evotor/framework/domain/DomainAttributeValue.kt
> +        val dictionaryName: String? = null,
потому что здесь мы храним dictionaryName, а не attributeName

2018-04-18 14:49 UTC, khaustov1 commented on src/main/java/ru/evotor/framework/core/IntegrationManagerImpl.java
> +            } catch (RemoteException e) {
Убрать изменения, не связанные с характеристиками

2018-04-18 14:51 UTC, khaustov1 commented on src/main/java/ru/evotor/framework/core/action/datamapper/PositionMapper.java
> +                (Map<String, DomainAttributeValue>) bundle.getSerializable(KEY_ATTRIBUTES);
Serializable очень медленно работает на android и мы его не используем вообще

2018-04-19 11:09 UTC, khaustov1 commented on src/main/java/ru/evotor/framework/domain/DomainAttribute.kt
> +        val uuid: String? = null,
Убрать nullable

2018-04-19 11:10 UTC, khaustov1 commented on src/main/java/ru/evotor/framework/domain/DomainAttribute.kt
> +        val name: String? = null,
Убрать nullable

2018-04-19 11:12 UTC, khaustov1 commented on src/main/java/ru/evotor/framework/domain/DomainAttributeValue.kt
> +        val dictionaryUuid: String? = null,
Убрать nullable

2018-04-19 11:15 UTC, khaustov1 commented on src/main/java/ru/evotor/framework/domain/DomainAttributeValue.kt
> +        val dictionaryName: String? = null,
Используем для связывания значения и сущности атрибута

2018-04-19 11:17 UTC, khaustov1 commented on src/main/java/ru/evotor/framework/receipt/Position.java
> +            @Nullable Map<String, DomainAttributeValue> attributes
Поправим

2018-05-28 11:33 UTC, closed without merging