Attributes
evotor/integration-library pull request #141
Opened 2018-05-10 15:09 UTC by khaustov1

Added attributes to position object

2018-05-17 06:41 UTC, xcam commented on src/main/java/ru/evotor/framework/domain/AttributeValue.kt
> +            parcel.readString(),
не вижу закладок на будущее (версионирование)

2018-05-17 06:44 UTC, xcam commented on src/main/java/ru/evotor/framework/domain/AttributeValue.kt
> +) : Parcelable {
нужно ли его вообще делать Parcelable?

2018-05-17 06:45 UTC, xcam commented on src/main/java/ru/evotor/framework/domain/Attribute.kt
> +        var attributeValues: List<AttributeValue>? = null
почему он nullable?
Должен ли вообще аттрибут иметь список значений в себе или лучше полумачть их отдельно?

2018-05-17 06:46 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/Position.java
>      public Position(
не надо плодить конструкторы - нужно использовать builder

2018-05-17 06:47 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/Position.java
> +    public Map<String, AttributeValue> getAttributes() {
что является ключом?

2018-05-17 06:47 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/Position.java
> +     * @return атрибуты позиции
не аттрибуты, а значения аттрибутов?

2018-05-17 06:47 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/Position.java
> +        public Builder setAttributes(@Nullable Map<String, AttributeValue> attributes) {
javadoc?

2018-05-17 06:49 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/Position.java
> +    @Override
зачем было переносить в конец класса? Теперь в середине класса между методов определен другой класс - некрасиво

2018-05-17 06:49 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/Position.java
> +        dest.writeInt(this.attributes != null ? this.attributes.size() : 0);
нет записи версии

2018-05-17 06:50 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/Position.java
> +        readAdditionalFields(in.readInt(), in);
совместимость все таки ломается (

2018-05-17 06:51 UTC, xcam requested changes
есть замечания

2018-07-03 09:04 UTC, khaustov1 commented on src/main/java/ru/evotor/framework/domain/AttributeValue.kt
> +) : Parcelable {
Да

2018-07-03 09:35 UTC, khaustov1 commented on src/main/java/ru/evotor/framework/receipt/Position.java
> +    @Override
+

2018-07-03 09:40 UTC, khaustov1 commented on src/main/java/ru/evotor/framework/receipt/Position.java
> +        public Builder setAttributes(@Nullable Map<String, AttributeValue> attributes) {
У вас в билдере нет ни одного метода или поля с javadoc

2018-07-03 09:41 UTC, khaustov1 commented on src/main/java/ru/evotor/framework/receipt/Position.java
>      public Position(
Согласен

2018-07-09 13:32 UTC, xcam commented on src/main/java/ru/evotor/framework/domain/Attribute.kt
> +        parcel.writeString(uuid)
версионирование

2018-07-09 15:41 UTC, xcam commented on src/main/java/ru/evotor/framework/domain/AttributeWithValues.kt
> +        val version: Int = 1,
зачем она в конструкторе

2018-07-09 15:41 UTC, xcam commented on src/main/java/ru/evotor/framework/domain/AttributeValue.kt
> +const val VERSION = 1
private

2018-07-09 21:25 UTC, xcam commented on src/main/java/ru/evotor/framework/domain/AttributeValue.kt
> +            val dataSize = parcel.readInt()
должна использоваться - конкретно пропускать все неиспользованные данные. В противном случае при чтении версии 2 получишь проблему

2018-07-09 21:26 UTC, xcam commented on src/main/java/ru/evotor/framework/domain/AttributeWithValues.kt
> +            val dataSize = parcel.readInt()
должна использоваться - конкретно пропускать все неиспользованные данные. В противном случае при чтении версии 2 получишь проблему

2018-07-09 21:28 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/Position.java
> +        boolean isVersionGreaterThanCurrent = false;
не нужна?

2018-07-09 21:28 UTC, xcam requested changes
см комментарии

2018-07-09 21:40 UTC, xcam approved these changes

2018-07-09 21:40 UTC, merged