STAPI-197: Added identifier (rrn) to the Payment object.
evotor/integration-library pull request #142
Opened 2018-05-15 08:14 UTC by K1rakishou

2018-05-17 07:29 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/Payment.kt
> +         * rrn
Идентификатор платежа в платежной системе (RRN для оплаты картой)

2018-05-17 07:30 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/ReceiptApi.kt
> +                cursor.getString(cursor.getColumnIndex(PaymentTable.COLUMN_IDENTIFIER))
колонки может не быть (если evopos старой версии) - нужно сделать защиту от этого

2018-05-17 07:30 UTC, xcam requested changes
см комментарии

2018-05-17 07:39 UTC, K1rakishou commented on src/main/java/ru/evotor/framework/receipt/Payment.kt
> +         * rrn
+

2018-05-17 07:39 UTC, K1rakishou commented on src/main/java/ru/evotor/framework/receipt/ReceiptApi.kt
> +                cursor.getString(cursor.getColumnIndex(PaymentTable.COLUMN_IDENTIFIER))
"+"

2018-05-21 09:55 UTC, xcam approved these changes

2018-05-21 09:55 UTC, merged