Broadcast Receiver Wrapper
evotor/integration-library pull request #155
Opened 2018-07-25 10:19 UTC by ArtemiyDmtrvch

2018-07-25 11:00 UTC, remiel-undead submitted a review, later dismissed

2018-07-26 13:14 UTC, xcam commented on src/main/java/ru/evotor/framework/core/action/broadcast/AbstractBroadcastReceiver.kt
> +    final override fun onReceive(p0: Context, p1: Intent) {
имена параметров непонятны

2018-07-26 13:14 UTC, xcam commented on src/main/java/ru/evotor/framework/core/action/broadcast/AbstractBroadcastReceiver.kt
> +    lateinit var context: Context
не надо хранить ссылку на контекст

2018-07-26 13:16 UTC, xcam commented on src/main/java/ru/evotor/framework/core/action/broadcast/CashDrawerBroadcastReceiver.kt
> +    protected abstract fun handleCashDrawerOpenedEvent(cashDrawerId: Int)
допиши какие intent-filter надо прописать в AndroidManifest

2018-07-26 13:21 UTC, xcam commented on src/main/java/ru/evotor/framework/core/action/broadcast/CashDrawerBroadcastReceiver.kt
> +abstract class CashDrawerBroadcastReceiver : AbstractBroadcastReceiver() {
может описать здесь как его использовать? Типа унаследуйтесь, переопределите метод такой-то, в андроид манифесте пропишите интент фильтр и тд?

2018-07-26 13:22 UTC, xcam commented on src/main/java/ru/evotor/framework/core/action/broadcast/CashOperationBroadcastReceiver.kt
> +    final override fun onEvent(action: String, bundle: Bundle) {
protected?

2018-07-26 13:24 UTC, xcam commented on src/main/java/ru/evotor/framework/core/action/broadcast/ReceiptBroadcastReceiver.kt
> +        private val actionPositionEdited: String,
добавление оплаты, начисление скидки, разбитие на печатные группы, начисление скидки и тд тут появятся?

2018-07-26 13:26 UTC, xcam requested changes
нужно исправить замечания

2018-07-27 09:29 UTC, ArtemiyDmtrvch commented on src/main/java/ru/evotor/framework/core/action/broadcast/CashOperationBroadcastReceiver.kt
> +    final override fun onEvent(action: String, bundle: Bundle) {
-

2018-07-30 10:42 UTC, ArtemiyDmtrvch commented on src/main/java/ru/evotor/framework/core/action/broadcast/AbstractBroadcastReceiver.kt
> +    final override fun onReceive(p0: Context, p1: Intent) {
исправил

2018-07-30 10:42 UTC, ArtemiyDmtrvch commented on src/main/java/ru/evotor/framework/core/action/broadcast/AbstractBroadcastReceiver.kt
> +    lateinit var context: Context
исправил

2018-07-30 10:42 UTC, ArtemiyDmtrvch commented on src/main/java/ru/evotor/framework/core/action/broadcast/CashDrawerBroadcastReceiver.kt
> +    protected abstract fun handleCashDrawerOpenedEvent(cashDrawerId: Int)
дописал

2018-07-30 10:43 UTC, ArtemiyDmtrvch commented on src/main/java/ru/evotor/framework/core/action/broadcast/ReceiptBroadcastReceiver.kt
> +        private val actionPositionEdited: String,
если броадкасты, то да

2018-07-30 10:44 UTC, ArtemiyDmtrvch commented on src/main/java/ru/evotor/framework/core/action/broadcast/CashDrawerBroadcastReceiver.kt
> +abstract class CashDrawerBroadcastReceiver : AbstractBroadcastReceiver() {
ну вот ща вроде нормально написано

2018-07-30 13:45 UTC, HeyAlex submitted a review, later dismissed

2018-10-08 11:07 UTC, closed without merging