Stapi 290
evotor/integration-library pull request #186
Opened 2018-11-29 15:24 UTC by ArtemiyDmtrvch

2018-12-03 07:34 UTC, xcam commented on src/main/java/ru/evotor/framework/FiscalDocument.kt
> +    abstract val documentNumber: Long
зачем приставка document?

2018-12-03 07:35 UTC, xcam commented on src/main/java/ru/evotor/framework/Document.kt
> +    protected open val uuid: UUID? = null
какой uuid будет у fiscaldocument?

2018-12-03 07:36 UTC, xcam commented on src/main/java/ru/evotor/framework/core/action/datamapper/ChangesMapper.kt
> +    private const val KEY_CHANGE_TYPE = "formationMethod"
обратная совместимость нарушена?

2018-12-03 07:37 UTC, xcam commented on src/main/java/ru/evotor/framework/core/action/datamapper/PrintExtraPlaceMapper.kt
> +    private const val KEY_TYPE = "formationMethod"
обратная совместимость нарушена?

2018-12-03 07:37 UTC, xcam commented on src/main/java/ru/evotor/framework/core/action/datamapper/PrintGroupMapper.java
> +    private static final String KEY_TYPE = "formationMethod";
обратная совместимость нарушена?

2018-12-03 07:37 UTC, xcam commented on src/main/java/ru/evotor/framework/mapper/DocumentMapper.kt
> +       // this.putSerializable(KEY_UUID, document.uuid)
это почему?

2018-12-03 07:39 UTC, xcam commented on src/main/java/ru/evotor/framework/mapper/FiscalDocumentMapper.kt
> +internal object FiscalDocumentMapper {
небольшая каша получается. Я бы предпочел чтобы маппер для создания из курсора и bundle были разделены

2018-12-03 07:40 UTC, xcam commented on src/main/java/ru/evotor/framework/mapper/FiscalDocumentMapper.kt
> +    fun readCreationDate(cursor: Cursor): Date? = cursor.optString(KEY_CREATION_DATE)?.let { Date(it.toLong()) }
что будет с датой если часовой пояс на терминале изменится?

2018-12-03 07:41 UTC, xcam commented on src/main/java/ru/evotor/framework/provider/FiscalDocumentContract.kt
> +    private const val AUTHORITY = "ru.evotor.framework.document.fiscal"
может лучше сделать Uri.parse("content://$AUTHORITY/fiscal")?

2018-12-03 07:42 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/FiscalReceipt.kt
> +        @FiscalRequisite(tag = FiscalDocument.TAG_DOCUMENT_NUMBER, isPrinted = true, isSentToOfd = true)
является ли здесь константа более читаемой чем просто число?

2018-12-03 07:43 UTC, xcam commented on src/main/java/ru/evotor/framework/FiscalRequisite.kt
> +        val isSentToOfd: Boolean
сейчас всегда true. Может стоит сделать значение по умолчанию и не указывать везде?

2018-12-03 07:45 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/ReceiptApi.kt
> +            context.contentResolver.query(FiscalReceiptContract.URI, null, null, arrayOf(receiptUuid), null)
через FiscalReceipt.Query это сделать нельзя?

2018-12-03 07:46 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/mapper/FiscalReceiptMapper.kt
> +          //      uuid = DocumentMapper.readUuid(it) ?: return null,
?

2018-12-03 07:46 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/mapper/FiscalReceiptMapper.kt
> +              //  uuid = DocumentMapper.readUuid(cursor) ?: return null,
?

2018-12-03 07:47 UTC, xcam requested changes
см комментарии

2018-12-03 14:37 UTC, ArtemiyDmtrvch commented on src/main/java/ru/evotor/framework/FiscalDocument.kt
> +    abstract val documentNumber: Long
потому что много что ещё может иметь number

2018-12-03 14:37 UTC, ArtemiyDmtrvch commented on src/main/java/ru/evotor/framework/core/action/datamapper/ChangesMapper.kt
> +    private const val KEY_CHANGE_TYPE = "formationMethod"
ай ай ай этого быть не должно было

2018-12-03 14:38 UTC, ArtemiyDmtrvch commented on src/main/java/ru/evotor/framework/core/action/datamapper/PrintExtraPlaceMapper.kt
> +    private const val KEY_TYPE = "formationMethod"
ай ай ай да как же так то

2018-12-03 14:38 UTC, ArtemiyDmtrvch commented on src/main/java/ru/evotor/framework/core/action/datamapper/PrintGroupMapper.java
> +    private static final String KEY_TYPE = "formationMethod";
ай ай ай фейл, фейл, не спорю. Грёбаный рефактор, кто его только просил об этом

2018-12-03 14:39 UTC, ArtemiyDmtrvch commented on src/main/java/ru/evotor/framework/mapper/FiscalDocumentMapper.kt
> +internal object FiscalDocumentMapper {
а вот с этим не соглашусь

2018-12-03 14:40 UTC, ArtemiyDmtrvch commented on src/main/java/ru/evotor/framework/mapper/FiscalDocumentMapper.kt
> +    fun readCreationDate(cursor: Cursor): Date? = cursor.optString(KEY_CREATION_DATE)?.let { Date(it.toLong()) }
0_0 wat?

2018-12-03 14:41 UTC, ArtemiyDmtrvch commented on src/main/java/ru/evotor/framework/provider/FiscalDocumentContract.kt
> +    private const val AUTHORITY = "ru.evotor.framework.document.fiscal"
ну у документа и фискального документа разные поля, поэтому я думал, разные контент провайдеры будут, от этого и разные ауторити

2018-12-03 14:42 UTC, ArtemiyDmtrvch commented on src/main/java/ru/evotor/framework/receipt/FiscalReceipt.kt
> +        @FiscalRequisite(tag = FiscalDocument.TAG_DOCUMENT_NUMBER, isPrinted = true, isSentToOfd = true)
канеш! Благодаря константам, у нас всегда будет список всех фискальных тегов в модели документа, и можно будет по ним искать поля

2018-12-03 14:45 UTC, ArtemiyDmtrvch commented on src/main/java/ru/evotor/framework/FiscalRequisite.kt
> +        val isSentToOfd: Boolean
ох да зачем, все равно потом если хоть одно поле добавится, где не везде true, все придется переделывать. А так уже сделано и вродь не мешает

2018-12-03 14:47 UTC, ArtemiyDmtrvch commented on src/main/java/ru/evotor/framework/receipt/ReceiptApi.kt
> +            context.contentResolver.query(FiscalReceiptContract.URI, null, null, arrayOf(receiptUuid), null)
нит, ты можешь достать только по uuid. никакой фильтрации не предусмотрено в псе

2018-12-03 14:52 UTC, ArtemiyDmtrvch commented on src/main/java/ru/evotor/framework/Document.kt
> +    protected open val uuid: UUID? = null
свой

2018-12-03 14:53 UTC, ArtemiyDmtrvch commented on src/main/java/ru/evotor/framework/Document.kt
> +    protected open val uuid: UUID? = null
не всм один uuid для всех обычных документов и другой для всех фискальных

2018-12-03 14:53 UTC, ArtemiyDmtrvch commented on src/main/java/ru/evotor/framework/Document.kt
> +    protected open val uuid: UUID? = null
прост если использовать наследование, то придется его переопределять

2018-12-03 15:00 UTC, ArtemiyDmtrvch commented on src/main/java/ru/evotor/framework/mapper/DocumentMapper.kt
> +       // this.putSerializable(KEY_UUID, document.uuid)
не понял вопроса

2018-12-04 09:14 UTC, xcam commented on src/main/java/ru/evotor/framework/Document.kt
> +    protected open val uuid: UUID? = null
т.е мы будем его генерировать? Или это закладка на будущее и он пока всегда null будет?

2018-12-04 09:15 UTC, xcam commented on src/main/java/ru/evotor/framework/mapper/DocumentMapper.kt
> +       // this.putSerializable(KEY_UUID, document.uuid)
почему закомментировано?

2018-12-04 09:17 UTC, xcam commented on src/main/java/ru/evotor/framework/FiscalRequisite.kt
> +        val isSentToOfd: Boolean
val isSentToOfd: Boolean = true
и когда появится false, то его нужно будет указать только там где оно false

2018-12-04 09:18 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/ReceiptApi.kt
> +            context.contentResolver.query(FiscalReceiptContract.URI, null, null, arrayOf(receiptUuid), null)
тогда зачем FiscalReceipt.Query? Оно работает?

2018-12-04 09:18 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/mapper/FiscalReceiptMapper.kt
> +          //      uuid = DocumentMapper.readUuid(it) ?: return null,
почему закомментировано

2018-12-04 09:18 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/mapper/FiscalReceiptMapper.kt
> +              //  uuid = DocumentMapper.readUuid(cursor) ?: return null,
почему закомментировано

2018-12-04 09:23 UTC, xcam commented on src/main/java/ru/evotor/framework/mapper/FiscalDocumentMapper.kt
> +    fun readCreationDate(cursor: Cursor): Date? = cursor.optString(KEY_CREATION_DATE)?.let { Date(it.toLong()) }
дата в long не учитывает часовой пояс. В итоге у тебя продажа была совершена в 12:00 по Владивостоку. Затем терминал уехал в Москву и получается что продажа была в 1:00, хотя она не должна была поменяться

2018-12-04 09:25 UTC, ArTemmey commented on src/main/java/ru/evotor/framework/Document.kt
> +    protected open val uuid: UUID? = null
FutureFeature указывает на то, что фича появится в будущем. Да, это закладка на будущее

2018-12-04 09:26 UTC, ArTemmey commented on src/main/java/ru/evotor/framework/mapper/DocumentMapper.kt
> +       // this.putSerializable(KEY_UUID, document.uuid)
потому что uuid еще не введен, это FutureFeature, но это конкретно можно удалить, да

2018-12-04 10:24 UTC, remiel-undead commented on src/main/java/ru/evotor/framework/mapper/FiscalDocumentMapper.kt
> +internal object FiscalDocumentMapper {
если вспомнить, как уродливо выглядели FromQwertyToZxMapper, FromAsdfToZxMapper и т.п., тоже не хочется плодить кучу классов, которые даже назвать порой не знаешь как; пусть даже 50 и более методов будет с похожими сигнатурами

2018-12-04 10:25 UTC, remiel-undead commented on src/main/java/ru/evotor/framework/mapper/FiscalDocumentMapper.kt
> +internal object FiscalDocumentMapper {
так что я за вариант @ArtemiyDmtrvch

2018-12-04 10:47 UTC, ArtemiyDmtrvch commented on src/main/java/ru/evotor/framework/mapper/FiscalDocumentMapper.kt
> +    fun readCreationDate(cursor: Cursor): Date? = cursor.optString(KEY_CREATION_DATE)?.let { Date(it.toLong()) }
поправил

2018-12-04 10:49 UTC, ArtemiyDmtrvch commented on src/main/java/ru/evotor/framework/receipt/ReceiptApi.kt
> +            context.contentResolver.query(FiscalReceiptContract.URI, null, null, arrayOf(receiptUuid), null)
нет, там сверху аннотация - FutureFeature, типа будет работать в будущем. А пока что это приватный класс

2018-12-04 10:49 UTC, ArtemiyDmtrvch commented on src/main/java/ru/evotor/framework/receipt/mapper/FiscalReceiptMapper.kt
> +          //      uuid = DocumentMapper.readUuid(it) ?: return null,
удалил

2018-12-04 10:49 UTC, ArtemiyDmtrvch commented on src/main/java/ru/evotor/framework/receipt/mapper/FiscalReceiptMapper.kt
> +              //  uuid = DocumentMapper.readUuid(cursor) ?: return null,
удалил

2018-12-04 10:52 UTC, ArtemiyDmtrvch commented on src/main/java/ru/evotor/framework/FiscalRequisite.kt
> +        val isSentToOfd: Boolean
то, что по умолчанию true, не очевидно.

2018-12-05 14:07 UTC, xcam commented on src/main/java/ru/evotor/framework/mapper/FiscalDocumentMapper.kt
> +    private const val FISCAL_DATE_PATTERN = "ddMMyyyyhhmm"
HH:(00-23) will look like 00, 01..23.
hh:(01-12 in AM/PM) will look like 01, 02..12.
должно быть HH

2018-12-05 14:10 UTC, ArtemiyDmtrvch commented on src/main/java/ru/evotor/framework/mapper/FiscalDocumentMapper.kt
> +    private const val FISCAL_DATE_PATTERN = "ddMMyyyyhhmm"
пофиксил :з

2018-12-05 14:12 UTC, xcam approved these changes

2018-12-05 14:12 UTC, merged