JavaDoc поддержка новых терминов ФФД 1.05 и переход на 20% налоговую ставку
evotor/integration-library pull request #189
Opened 2018-12-06 08:18 UTC by Lytkini

2018-12-06 10:27 UTC, notxcain commented on src/main/java/ru/evotor/framework/receipt/TaxNumber.kt
> +     * Основная ставка 18%. С первого января 2019 года может указывать как на 18%, так и на 20% ставку.
А почему не завести `VAT_20`?

2018-12-06 10:48 UTC, Lytkini commented on src/main/java/ru/evotor/framework/receipt/TaxNumber.kt
> +     * Основная ставка 18%. С первого января 2019 года может указывать как на 18%, так и на 20% ставку.
@xcam, прокомментируй, пожалуйста.

2019-01-23 07:47 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/TaxNumber.kt
> +     * Основная ставка 18%. С первого января 2019 года может указывать как на 18%, так и на 20% ставку.
Потому что тогда каждому клиенту придется руками у товаров указать новую ставку или каждой ТУ придется перегрузить товары с новыми ставками

2019-01-31 15:12 UTC, xcam commented on src/main/java/ru/evotor/framework/payment/PaymentType.java
> +     * Наличными срдествами
опечатка

2019-01-31 15:12 UTC, xcam requested changes
Есть замечание

2019-01-31 15:27 UTC, Lytkini commented on src/main/java/ru/evotor/framework/payment/PaymentType.java
> +     * Наличными срдествами
Поправил.

2019-05-29 11:13 UTC, merged