Stdev-2187
evotor/integration-library pull request #235
Opened 2019-05-31 14:25 UTC by flooduk

Изменение точки интеграции, возвращающей PrintGroups

2019-06-03 08:38 UTC, xcam requested changes

2019-06-03 08:38 UTC, xcam commented on src/main/java/ru/evotor/framework/ParcelableUtils.kt
> +            setDataPosition(startDataPosition + dataSize)
я думаю, что здесь нужно дать возможность считать данные. Иначе старые приложения сразу перестают работать, хотя мы можем их поддержать. Как пример - добавление текущих полей. Для старых интеграций значение по умолчанию вполне решает задачу

2019-06-03 08:38 UTC, xcam commented on src/main/java/ru/evotor/framework/core/action/datamapper/PrintGroupMapper.java
> +        Purchaser purchaser = bundle.getParcelable(KEY_PURCHASER);
я предпочитаю в mapper классах не использовать parcelable. Вместо него предпочтительней чистые bundle. Так легче перемещать классы по пакетам, proguard не ломает ничего и версионирование выглядит проще

2019-06-03 08:38 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/PrintGroup.java
>      public PrintGroup(
давай пометим как Deprecated?

2019-06-03 08:38 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/ReceiptApi.kt
> +        val purchaserName = try {
можно заиспользовать optString https://github.com/evotor/integration-library/blob/1a6b74e77e04b721f9536083949494ad3df04eb3/src/main/java/ru/evotor/framework/KotlinUtils.kt#L62

2019-06-03 08:38 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/formation/event/handler/service/SellIntegrationService.kt
> +import ru.evotor.framework.receipt.formation.event.ReturnPurchaserRequisitesForPrintGroupRequestedEvent
та же история в возврате, покупке и возврате покупки

2019-06-03 09:18 UTC, flooduk commented on src/main/java/ru/evotor/framework/ParcelableUtils.kt
> +            setDataPosition(startDataPosition + dataSize)
fix

2019-06-03 09:18 UTC, flooduk commented on src/main/java/ru/evotor/framework/core/action/datamapper/PrintGroupMapper.java
> +        Purchaser purchaser = bundle.getParcelable(KEY_PURCHASER);
fix

2019-06-03 09:18 UTC, flooduk commented on src/main/java/ru/evotor/framework/receipt/PrintGroup.java
>      public PrintGroup(
fix

2019-06-03 09:18 UTC, flooduk commented on src/main/java/ru/evotor/framework/receipt/ReceiptApi.kt
> +        val purchaserName = try {
fix

2019-06-03 10:03 UTC, flooduk commented on src/main/java/ru/evotor/framework/receipt/formation/event/handler/service/SellIntegrationService.kt
> +import ru.evotor.framework.receipt.formation.event.ReturnPurchaserRequisitesForPrintGroupRequestedEvent
fix

2019-06-04 05:41 UTC, xcam approved these changes

2019-06-04 05:41 UTC, merged