STDEV-3264
evotor/integration-library pull request #275
Opened 2019-10-23 08:22 UTC by apliter

Added ACTION_DISCOUNT_SCREEN_ADDITIONAL_ITEMS for Buy\Buyback receipt
Added receiptDiscountEvent for Buy\Buyback receipt

2019-10-23 08:52 UTC, flooduk commented on build.gradle
> +        versionName "STDEV-1901"
ой

2019-10-23 08:52 UTC, flooduk submitted a review, later dismissed

2019-10-23 09:17 UTC, flooduk submitted a review, later dismissed

2019-10-25 06:45 UTC, flooduk submitted a review, later dismissed

2019-11-06 08:00 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/formation/event/handler/service/BuyIntegrationService.kt
> +    open fun handleEvent(event: DiscountScreenAdditionalItemsEvent): IBundlable? = null
что я должен вернуть из этого метода? Какие данные?

2019-11-06 08:03 UTC, xcam commented on src/main/java/ru/evotor/framework/core/action/event/receipt/discount/ReceiptDiscountEvent.java
> +    public static final String NAME_PAYBACK_BY_SUM_RECEIPT = "evo.v2.receipt.paybackBySum.receiptDiscount";
понятие BySum думаю не стоит вводить. Скорее стоит обособить возврат на основании

2019-11-06 08:04 UTC, xcam requested changes
см комментарии

2019-11-06 09:23 UTC, apliter commented on src/main/java/ru/evotor/framework/core/action/event/receipt/discount/ReceiptDiscountEvent.java
> +    public static final String NAME_PAYBACK_BY_SUM_RECEIPT = "evo.v2.receipt.paybackBySum.receiptDiscount";
Нельзя так. 
Причина: В возврате на основании чека не должны быть доступны интеграции ReceiptDiscountEvent, а в возврате без чека (BY_SUM) интеграции должны быть видны. 
Чем плохо разделение возвратов?

2019-11-06 13:44 UTC, apliter commented on src/main/java/ru/evotor/framework/receipt/formation/event/handler/service/BuyIntegrationService.kt
> +    open fun handleEvent(event: DiscountScreenAdditionalItemsEvent): IBundlable? = null
+

2019-11-06 13:44 UTC, apliter commented on src/main/java/ru/evotor/framework/core/action/event/receipt/discount/ReceiptDiscountEvent.java
> +    public static final String NAME_PAYBACK_BY_SUM_RECEIPT = "evo.v2.receipt.paybackBySum.receiptDiscount";
+

2019-11-19 10:12 UTC, flooduk commented on src/main/java/ru/evotor/framework/core/action/event/receipt/discount/ReceiptDiscountEvent.java
> +     * Скидка начислена на чек покупки без основания.
на чек покупки. "без основания" - лишнее

2019-11-19 19:23 UTC, xcam commented on src/main/java/ru/evotor/framework/inventory/ProductType.java
> +    MEDICINE_MARKED
Это как сюда попало?

2019-11-19 19:24 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/Position.java
> +        public Builder toMedicineMarked(
это как сюда попало?

2019-11-19 19:25 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/Position.java
> +        private void setMarkedParams(String mark) {
а когда добавятся параметры рецепта для лекарств не придется обратно все откатывать?

2019-11-19 19:28 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/formation/event/handler/service/PaybackIntegrationService.kt
> +    open fun handleEvent(event: DiscountScreenAdditionalItemsEvent): DiscountScreenAdditionalItemsEvent? = null
т.е. я на входе получаю event и вернуть должен event? Кажется мне, что все таки ничего не надо возвращать

2019-11-20 08:18 UTC, apliter commented on src/main/java/ru/evotor/framework/core/action/event/receipt/discount/ReceiptDiscountEvent.java
> +     * Скидка начислена на чек покупки без основания.
+

2019-11-20 08:19 UTC, apliter commented on src/main/java/ru/evotor/framework/receipt/Position.java
> +        private void setMarkedParams(String mark) {
вернул

2019-11-20 08:19 UTC, apliter commented on src/main/java/ru/evotor/framework/inventory/ProductType.java
> +    MEDICINE_MARKED
откатил

2019-11-20 08:19 UTC, apliter commented on src/main/java/ru/evotor/framework/core/action/event/receipt/discount/ReceiptDiscountEvent.java
> +     * Скидка начислена на чек покупки без основания.
исправил

2019-11-20 08:50 UTC, apliter commented on src/main/java/ru/evotor/framework/receipt/formation/event/handler/service/PaybackIntegrationService.kt
> +    open fun handleEvent(event: DiscountScreenAdditionalItemsEvent): DiscountScreenAdditionalItemsEvent? = null
так как onEvent, в котором дергается две реализации handleEvent имеет тип возвращаемого результата
ReturnPurchaserRequisitesForPrintGroupRequestedEvent.Result? то во избежании проблем 
handleEvent для ACTION_DISCOUNT_SCREEN_ADDITIONAL_ITEMS, который не имеет результата, будет возвращать Nothing? = null

2019-11-29 09:16 UTC, flooduk approved these changes

2019-12-02 15:18 UTC, xcam approved these changes

2019-12-02 15:19 UTC, merged