Stdev 3284
evotor/integration-library pull request #306
Opened 2020-05-11 23:15 UTC by Khavronsky

Расширена Position добавлена поддержка новых тегов для продажи лекарств по рецептам

2020-05-18 08:41 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/MedicineAttribute.kt
> + * Дополнительные реквизиты ползователя, которые необходимы для формирования структурного тега 1084 (состоит из тегов 1085 и 1086)
опечатка в слове "пользователь"

2020-05-18 08:42 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/MedicineAttribute.kt
> +         * Значение дополнительного реквизита пользователя (тег 1086)
они все в один тег пишутся?
Плюс есть аннотация для фискальных тегов

2020-05-18 08:43 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/MedicineAttribute.kt
> +        val documentDate: String? = null,
я думаю тип поля должен быть Date а формат уже при передаче в ККМ выберется

2020-05-18 08:43 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/MedicineAttribute.kt
> +            parcel.writeString(preferentialDiscountType?.name)
версионирование нарушено

2020-05-18 08:44 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/MedicineAttribute.kt
> +        when (preferentialDiscountType) {
кажется, что это должно быть не в апи, а скрыто в глубинах терминала?

2020-05-18 08:45 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/MedicineAttribute.kt
> +            parcel.writeString(preferentialDiscountType?.name)
не нашел где поправлено чтение парсела

2020-05-18 08:46 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/MedicineAttribute.kt
> +        private const val MDLP_FULL_PARTIAL = "3108805"
а это зачем здесь? По моему это информация не апи?

2020-05-18 08:48 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/MedicineAttribute.kt
> +                            PreferentialDiscountType.valueOf(s)
тут может вылететь исключение. Для того чтобы этого не происходило у нас есть метод safeValueOf

2020-05-18 08:50 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/MedicineAttribute.kt
> +                when (version) {
если сюда придет значение 3, то создадим пустой объект. А могли бы все равно сделать объект

2020-05-18 08:51 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/Position.java
> +    private static final int VERSION = 5;
по моему это уже занято - подмержите develop

2020-05-18 08:52 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/position/PreferentialDiscount.kt
> +    enum class PreferentialDiscountType {
я не уверен что Discount - это хорошее определение здесь. Тем более что льготы оформляются не как скидка а как встречное предоставление

2020-05-18 08:53 UTC, xcam commented on src/main/java/ru/evotor/framework/core/action/datamapper/PositionMapper.java
> +import ru.evotor.framework.receipt.position.PreferentialDiscount;
в build.gradle нужно поднять значение версии, чтобы потом сделать обработку этого значения в pos

2020-05-18 08:53 UTC, xcam requested changes
см замечания

2020-05-18 09:06 UTC, Affordall commented on src/main/java/ru/evotor/framework/kkt/FiscalTags.kt
> +    const val ADDITIONAL_REQUISITE_TITLE = 1085
Не совсем понятное имя, в комментах упоминание пользователя

2020-05-18 09:06 UTC, Affordall commented on src/main/java/ru/evotor/framework/kkt/FiscalTags.kt
> +    const val ADDITIONAL_REQUISITE_VALUE = 1086
Не совсем понятное имя, в комментах упоминание пользователя

2020-05-19 08:19 UTC, Khavronsky commented on src/main/java/ru/evotor/framework/receipt/MedicineAttribute.kt
> + * Дополнительные реквизиты ползователя, которые необходимы для формирования структурного тега 1084 (состоит из тегов 1085 и 1086)
+

2020-05-19 08:20 UTC, Khavronsky commented on src/main/java/ru/evotor/framework/receipt/MedicineAttribute.kt
> +                            PreferentialDiscountType.valueOf(s)
Поправил

2020-05-19 08:20 UTC, Khavronsky commented on src/main/java/ru/evotor/framework/receipt/MedicineAttribute.kt
> +                when (version) {
Поправил

2020-05-19 08:20 UTC, Khavronsky commented on src/main/java/ru/evotor/framework/receipt/Position.java
> +    private static final int VERSION = 5;
Поправил

2020-05-19 08:20 UTC, Khavronsky commented on src/main/java/ru/evotor/framework/receipt/position/PreferentialDiscount.kt
> +    enum class PreferentialDiscountType {
Поправил

2020-05-19 08:20 UTC, Khavronsky commented on src/main/java/ru/evotor/framework/core/action/datamapper/PositionMapper.java
> +import ru.evotor.framework.receipt.position.PreferentialDiscount;
Поправил

2020-05-19 08:21 UTC, Khavronsky commented on src/main/java/ru/evotor/framework/kkt/FiscalTags.kt
> +    const val ADDITIONAL_REQUISITE_TITLE = 1085
Поправил

2020-05-19 08:21 UTC, Khavronsky commented on src/main/java/ru/evotor/framework/kkt/FiscalTags.kt
> +    const val ADDITIONAL_REQUISITE_VALUE = 1086
Поправил

2020-05-20 08:30 UTC, Khavronsky commented on src/main/java/ru/evotor/framework/receipt/MedicineAttribute.kt
> +        private const val MDLP_FULL_PARTIAL = "3108805"
Перенесено в пос

2020-05-20 08:30 UTC, Khavronsky commented on src/main/java/ru/evotor/framework/receipt/MedicineAttribute.kt
> +            parcel.writeString(preferentialDiscountType?.name)
исправлено

2020-05-20 08:30 UTC, Khavronsky commented on src/main/java/ru/evotor/framework/receipt/MedicineAttribute.kt
> +        when (preferentialDiscountType) {
перенесно в пос

2020-05-20 08:30 UTC, Khavronsky commented on src/main/java/ru/evotor/framework/receipt/MedicineAttribute.kt
> +        val documentDate: String? = null,
исправлено

2020-05-20 08:57 UTC, Khavronsky commented on src/main/java/ru/evotor/framework/receipt/MedicineAttribute.kt
> +         * Значение дополнительного реквизита пользователя (тег 1086)
исправлено

2020-05-21 08:58 UTC, Affordall commented on src/main/java/ru/evotor/framework/receipt/Position.java
> +        public Builder setPreferentialDiscount(@Nullable PreferentialMedicine preferentialMedicine) {
Что все таки правильней: PreferentialDiscount или PreferentialMedicine? Получается setter и getter имеют более абстрактное применение, но тогда почему в аргументы приходит конкретно preferentialMedicine? Может есть смысл переименовать getter и setter, если это поле используется только в Medicine

2020-05-21 08:58 UTC, Affordall commented on src/main/java/ru/evotor/framework/receipt/Position.java
>          //Preferential discount
Будет все-таки discount or medicine?

2020-05-21 08:58 UTC, Affordall commented on src/main/java/ru/evotor/framework/receipt/MedicineAttribute.kt
> +                        preferentialMedicineType = it.getString(KEY_PREFERENTIAL_DISCOUNT_TYPE)?.let { s ->
Здесь тоже лучше использовать безопасный метод для valueOf - > Utils.safeValueOf

2020-05-21 13:10 UTC, Khavronsky commented on src/main/java/ru/evotor/framework/receipt/Position.java
> +        public Builder setPreferentialDiscount(@Nullable PreferentialMedicine preferentialMedicine) {
поправил

2020-05-21 13:10 UTC, Khavronsky commented on src/main/java/ru/evotor/framework/receipt/Position.java
>          //Preferential discount
поправил

2020-05-21 13:10 UTC, Khavronsky commented on src/main/java/ru/evotor/framework/receipt/MedicineAttribute.kt
> +                        preferentialMedicineType = it.getString(KEY_PREFERENTIAL_DISCOUNT_TYPE)?.let { s ->
поправил

2020-05-23 13:53 UTC, xcam commented on src/main/java/ru/evotor/framework/core/action/datamapper/PositionMapper.java
> +                PreferentialMedicine.Companion.from(bundle.getBundle(KEY_PREFERENTIAL_MEDICINE));
Companion выглядит некрасиво. Чтобы от этого избавиться есть аннотация @JvmStatic

2020-05-23 13:56 UTC, xcam commented on src/main/java/ru/evotor/framework/core/action/datamapper/PositionMapper.java
> +    private static final String KEY_PREFERENTIAL_MEDICINE = "preferentialMedicine";
используется в методе Position from(@Nullable Bundle bundle), но не используется в методе Bundle toBundle(@Nullable Position position)

2020-05-23 14:00 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/MedicineAttribute.kt
> +        val documentNumber: String? = null,
какие правила у documentnumber,  documentDate, serialNumber? Могут ли быть номер документа, а дата нет? Если они либо есть все вместе, либо нет ни одного, то лучше в MedicineAttribute сделать поле document, которое будет Nullable, а внутри уже NonNull поля номер, дата и тд

2020-05-23 14:03 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/MedicineAttribute.kt
> +                        documentDate = Date(it.getLong(KEY_DOCUMENT_DATE)),
если у тебя в изначальном объекте documentDate = null, то будет записан 0 и потом при восстановлении из Bundle также считан 0. В итоге после восстановления всегда будет дата 1970 год

2020-05-23 14:05 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/MedicineAttribute.kt
> +                                documentDate = Date(parcel.readLong()),
если у тебя в изначальном объекте documentDate = null, то будет записан 0 и потом при восстановлении из Parcel также считан 0. В итоге после восстановления всегда будет дата 1970 год

2020-05-23 14:07 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/Position.java
> +        dest.writeBundle(this.preferentialMedicine != null ? this.preferentialMedicine.toBundle() : null);
Зависит от того что выйдет раньше - лекарства или передача ean. Если передача ean, то надо бы дописывать новые данные в конец, а не в середину

2020-05-23 14:07 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/Position.java
> +                readPreferentialDiscount(in);
Не Discount

2020-05-23 14:08 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/Position.java
> +            case 6: {
потерян classificationCode

2020-05-23 14:09 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/ReceiptApi.kt
> +        val documentDate: Date? = Date(cursor.optLong(PrintGroupSubTable.COLUMN_DOCUMENT_DATE) ?: 0)
по умолчанию должно быть null, а не 1970 год

2020-05-23 14:10 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/ReceiptApi.kt
> +                            subjectId = subjectId,
может ли быть MedicineAttribute без subjectId, но с данными по рецепту? Если да, то нужно изменить условие в if (subjectId != null)

2020-05-23 14:11 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/position/PreferentialMedicine.kt
> +        val discountValue: BigDecimal
тут надо discount?

2020-05-23 14:12 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/position/mapper/PreferentialMedicineMapper.kt
> +    private const val KEY_PREFERENTIAL_MEDICINE_TYPE = "DiscountType"
discount?

2020-05-23 14:14 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/position/mapper/PreferentialMedicineMapper.kt
> +            PreferentialMedicine(
получается что мы всегда возвращаем некоторый дефолтный PreferentialMedicine, даже для старх чеков из 2018 года?

2020-05-23 14:15 UTC, xcam requested changes
Есть замечания

2020-05-23 15:03 UTC, merged

2020-05-26 18:30 UTC, Khavronsky commented on src/main/java/ru/evotor/framework/core/action/datamapper/PositionMapper.java
> +                PreferentialMedicine.Companion.from(bundle.getBundle(KEY_PREFERENTIAL_MEDICINE));
поправил

2020-05-26 18:30 UTC, Khavronsky commented on src/main/java/ru/evotor/framework/core/action/datamapper/PositionMapper.java
> +    private static final String KEY_PREFERENTIAL_MEDICINE = "preferentialMedicine";
поправил

2020-05-26 18:30 UTC, Khavronsky commented on src/main/java/ru/evotor/framework/receipt/MedicineAttribute.kt
> +        val documentNumber: String? = null,
поправил

2020-05-26 18:31 UTC, Khavronsky commented on src/main/java/ru/evotor/framework/receipt/MedicineAttribute.kt
> +                        documentDate = Date(it.getLong(KEY_DOCUMENT_DATE)),
поправил

2020-05-26 18:31 UTC, Khavronsky commented on src/main/java/ru/evotor/framework/receipt/MedicineAttribute.kt
> +                                documentDate = Date(parcel.readLong()),
поправил

2020-05-26 18:32 UTC, Khavronsky commented on src/main/java/ru/evotor/framework/receipt/Position.java
> +                readPreferentialDiscount(in);
Поправил

2020-05-26 18:32 UTC, Khavronsky commented on src/main/java/ru/evotor/framework/receipt/Position.java
> +            case 6: {
Поправил

2020-05-26 18:32 UTC, Khavronsky commented on src/main/java/ru/evotor/framework/receipt/ReceiptApi.kt
> +        val documentDate: Date? = Date(cursor.optLong(PrintGroupSubTable.COLUMN_DOCUMENT_DATE) ?: 0)
Поправил

2020-05-26 18:33 UTC, Khavronsky commented on src/main/java/ru/evotor/framework/receipt/ReceiptApi.kt
> +                            subjectId = subjectId,
subjectId обязателен для продажи лекарств

2020-05-26 18:33 UTC, Khavronsky commented on src/main/java/ru/evotor/framework/receipt/position/PreferentialMedicine.kt
> +        val discountValue: BigDecimal
поправил

2020-05-26 18:34 UTC, Khavronsky commented on src/main/java/ru/evotor/framework/receipt/position/mapper/PreferentialMedicineMapper.kt
> +    private const val KEY_PREFERENTIAL_MEDICINE_TYPE = "DiscountType"
поправил

2020-05-26 18:43 UTC, Khavronsky commented on src/main/java/ru/evotor/framework/receipt/position/mapper/PreferentialMedicineMapper.kt
> +            PreferentialMedicine(
Действительно, нехорошо получилось...
Поправил

2020-05-26 18:57 UTC, Khavronsky commented on src/main/java/ru/evotor/framework/receipt/Position.java
> +        dest.writeBundle(this.preferentialMedicine != null ? this.preferentialMedicine.toBundle() : null);
Исправил