STDEV-5209
evotor/integration-library pull request #307
Opened 2020-05-12 12:33 UTC by apliter

Добавлено поле "Классификационный код"

2020-05-12 13:26 UTC, maxViolet submitted a review, later dismissed

2020-05-12 13:39 UTC, xcam commented on src/main/java/ru/evotor/framework/inventory/InventoryApi.kt
> +                                        classificationCode = cursor.getString(cursor.getColumnIndex(ProductTable.ROW_CLASSIFICATION_CODE))
у нас были проблемы, когда в EvotorPOS не было этой колонки. Проверь пожалуйста, что в этом случае ничего не упадет

2020-05-12 13:40 UTC, xcam commented on src/main/java/ru/evotor/framework/core/action/datamapper/PositionMapper.java
> +    private static final String KEY_CLASSIFICATION_CODE = "classificationCode";
не мешало бы еще считывать его в методе public static Position from(@Nullable Bundle bundle) {

2020-05-12 13:43 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/Position.java
> +     * Классификационный код
тут надо более подробное описание. В каких случаях марка будет, в каких этот код. Да и "классификационный код" мало о чем говорит

2020-05-12 13:43 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/Position.java
> +     * Тег 1162
непонятно в каком формате нужно передавать сюда данные

2020-05-12 14:07 UTC, apliter commented on src/main/java/ru/evotor/framework/core/action/datamapper/PositionMapper.java
> +    private static final String KEY_CLASSIFICATION_CODE = "classificationCode";
+

2020-05-12 14:20 UTC, apliter commented on src/main/java/ru/evotor/framework/receipt/Position.java
> +     * Классификационный код
+

2020-05-12 14:20 UTC, apliter commented on src/main/java/ru/evotor/framework/receipt/Position.java
> +     * Тег 1162
+

2020-05-13 03:23 UTC, apliter commented on src/main/java/ru/evotor/framework/inventory/InventoryApi.kt
> +                                        classificationCode = cursor.getString(cursor.getColumnIndex(ProductTable.ROW_CLASSIFICATION_CODE))
заменил на optString

2020-05-13 06:50 UTC, xcam commented on src/main/java/ru/evotor/framework/inventory/ProductMapper.kt
> +                        classificationCode = cursor.getString(cursor.getColumnIndex(ProductTable.ROW_CLASSIFICATION_CODE))
optString?

2020-05-13 06:52 UTC, xcam commented on src/main/java/ru/evotor/framework/core/action/datamapper/PositionMapper.java
>      private static final String KEY_AGENT_REQUISITES = "agentRequisites";
в файле build.gradle нужно поднять def version

2020-05-13 06:56 UTC, xcam commented on src/main/java/ru/evotor/framework/core/action/datamapper/PositionMapper.java
>      private static final String KEY_AGENT_REQUISITES = "agentRequisites";
И еще я щас понял что ReceiptApi.createPosition метод собирает не полную позицию теперь (там и акциза не хватает с данными импорта)

2020-05-13 06:57 UTC, xcam requested changes
Оставил замечания

2020-05-14 14:58 UTC, apliter commented on src/main/java/ru/evotor/framework/inventory/ProductMapper.kt
> +                        classificationCode = cursor.getString(cursor.getColumnIndex(ProductTable.ROW_CLASSIFICATION_CODE))
+

2020-05-14 14:58 UTC, apliter commented on src/main/java/ru/evotor/framework/core/action/datamapper/PositionMapper.java
>      private static final String KEY_AGENT_REQUISITES = "agentRequisites";
+

2020-05-14 14:58 UTC, apliter commented on src/main/java/ru/evotor/framework/core/action/datamapper/PositionMapper.java
>      private static final String KEY_AGENT_REQUISITES = "agentRequisites";
+

2020-05-14 15:26 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/ReceiptApi.kt
> +        val excise = BigDecimal(cursor.getLong(cursor.getColumnIndex(PositionTable.COLUMN_EXCISE)))
тут NPE не вылетит? и что будет если нет такой колонки?

2020-05-14 15:27 UTC, xcam requested changes
см замечания

2020-05-14 15:32 UTC, xcam approved these changes

2020-05-14 15:32 UTC, merged