Stdev 5693
evotor/integration-library pull request #316
Opened 2020-07-13 11:20 UTC by Angeba

2020-08-07 10:08 UTC, Affordall approved these changes

2020-08-10 11:24 UTC, Affordall requested changes

2020-08-10 11:24 UTC, Affordall commented on src/main/java/ru/evotor/framework/receipt/formation/event/ReturnPositionsForBarcodeRequestedEvent.kt
> +            val positionsList: List<List<Position>>? = null,
Давай избавимся от старых val positions: List<Position>, и оставим только новый positionsList, чтобы не было дублирования

2020-08-10 11:24 UTC, Affordall commented on src/main/java/ru/evotor/framework/receipt/formation/event/ReturnPositionsForBarcodeRequestedEvent.kt
> +        constructor(
а здесь мы оставляем старый конструктор с positions: List<Position> и объявляем его deprecated

2020-08-10 11:24 UTC, Affordall commented on src/main/java/ru/evotor/framework/receipt/formation/event/ReturnPositionsForBarcodeRequestedEvent.kt
> +        ) : this(null, positions, iCanCreateNewProduct)
тут оборачиваем positions в новый positionsList

2020-08-10 11:24 UTC, Affordall commented on src/main/java/ru/evotor/framework/receipt/formation/event/ReturnPositionsForBarcodeRequestedEvent.kt
> +            if (!positions.isNullOrEmpty()) {
И соответственно здесь изменится логика обработки

2020-08-10 11:24 UTC, Affordall commented on src/main/java/ru/evotor/framework/receipt/formation/event/ReturnPositionsForBarcodeRequestedEvent.kt
> +                val positionsList = mutableListOf<List<Position>>()
и тут

2020-08-10 11:30 UTC, Angeba commented on src/main/java/ru/evotor/framework/receipt/formation/event/ReturnPositionsForBarcodeRequestedEvent.kt
> +            val positionsList: List<List<Position>>? = null,
Ок

2020-08-10 11:32 UTC, Angeba commented on src/main/java/ru/evotor/framework/receipt/formation/event/ReturnPositionsForBarcodeRequestedEvent.kt
> +        constructor(
+

2020-08-11 06:23 UTC, Angeba commented on src/main/java/ru/evotor/framework/receipt/formation/event/ReturnPositionsForBarcodeRequestedEvent.kt
> +        ) : this(null, positions, iCanCreateNewProduct)
+

2020-08-11 06:23 UTC, Angeba commented on src/main/java/ru/evotor/framework/receipt/formation/event/ReturnPositionsForBarcodeRequestedEvent.kt
> +            if (!positions.isNullOrEmpty()) {
Да, немного изменилась. Поправила.

2020-08-11 06:31 UTC, Angeba commented on src/main/java/ru/evotor/framework/receipt/formation/event/ReturnPositionsForBarcodeRequestedEvent.kt
> +                val positionsList = mutableListOf<List<Position>>()
+

2020-08-11 09:41 UTC, Affordall approved these changes

2020-08-11 12:49 UTC, Affordall approved these changes

2020-08-12 12:12 UTC, merged