Fixes and updates
evotor/integration-library pull request #321
Opened 2020-09-02 16:51 UTC by Affordall

- increase buildToolsVersion
- increase kotlin version to 1.4.0
- increase android gradle plugin version to 4.0.1
- correct dependencies
- fix sonar issues
- fix missing break in Medicine
- fix auto-close cursor

2020-09-04 12:42 UTC, xcam commented on src/main/java/ru/evotor/framework/inventory/InventoryApi.kt
> +            )?.use {
а там toList курсор не закрывает?

2020-09-04 12:43 UTC, xcam commented on src/main/java/ru/evotor/framework/inventory/InventoryApi.kt
> +                ?.use { cursor ->
catch потерял - теперь exception полетит наружу

2020-09-04 12:43 UTC, xcam commented on src/main/java/ru/evotor/framework/inventory/InventoryApi.kt
> -                    } catch (e: Exception) {
catch потерял - теперь exception полетит наружу

2020-09-04 12:43 UTC, xcam commented on src/main/java/ru/evotor/framework/inventory/InventoryApi.kt
> -                    } catch (e: Exception) {
catch потерял - теперь exception полетит наружу

2020-09-04 12:44 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/ReceiptApi.kt
> +        )?.use{
мы правда хотим отдавать наружу закрытый курсор?

2020-09-04 12:45 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/ReceiptApi.kt
> +                    ?.use {
мы правда хотим отдавать наружу закрытый курсор?

2020-09-04 12:45 UTC, xcam commented on src/main/java/ru/evotor/framework/users/UserApi.kt
> -                    } catch (e: Exception) {
catch потерялся

2020-09-04 12:45 UTC, xcam commented on src/main/java/ru/evotor/framework/users/UserApi.kt
> -                    } catch (e: Exception) {
catch потерялся

2020-09-04 12:45 UTC, xcam commented on src/main/java/ru/evotor/framework/users/UserApi.kt
> -                    } catch (e: Exception) {
catch потерялся

2020-09-04 12:46 UTC, xcam commented on src/main/java/ru/evotor/framework/users/UserApi.kt
> -                    } catch (e: Exception) {
catch потерялся

2020-09-04 12:46 UTC, xcam requested changes
есть замечания

2020-09-09 17:09 UTC, Affordall commented on src/main/java/ru/evotor/framework/inventory/InventoryApi.kt
> -                    } catch (e: Exception) {
По-идее, оно и должно лететь наружу. Но я верну

2020-09-10 08:28 UTC, Affordall commented on src/main/java/ru/evotor/framework/inventory/InventoryApi.kt
> +            )?.use {
нет

2020-09-10 08:39 UTC, Affordall commented on src/main/java/ru/evotor/framework/inventory/InventoryApi.kt
> +                ?.use { cursor ->
вернул

2020-09-10 08:39 UTC, Affordall commented on src/main/java/ru/evotor/framework/inventory/InventoryApi.kt
> -                    } catch (e: Exception) {
вернул

2020-09-10 08:40 UTC, Affordall commented on src/main/java/ru/evotor/framework/receipt/ReceiptApi.kt
> +        )?.use{
да, но вернул)

2020-09-10 08:40 UTC, Affordall commented on src/main/java/ru/evotor/framework/receipt/ReceiptApi.kt
> +                    ?.use {
вернул

2020-09-10 08:40 UTC, Affordall commented on src/main/java/ru/evotor/framework/users/UserApi.kt
> -                    } catch (e: Exception) {
вернул

2020-09-10 08:40 UTC, Affordall commented on src/main/java/ru/evotor/framework/users/UserApi.kt
> -                    } catch (e: Exception) {
вернул

2020-09-10 08:40 UTC, Affordall commented on src/main/java/ru/evotor/framework/users/UserApi.kt
> -                    } catch (e: Exception) {
вернул

2020-09-10 08:40 UTC, Affordall commented on src/main/java/ru/evotor/framework/users/UserApi.kt
> -                    } catch (e: Exception) {
вернул

2020-09-10 08:59 UTC, flooduk approved these changes, later dismissed

2020-09-15 15:17 UTC, closed without merging