MRK-166 Fix medicine tags
evotor/integration-library pull request #325
Opened 2020-09-15 15:54 UTC by Affordall

- Add fiscal tags
- Add default value to PreferentialMedicineType
- Add MedicineAttributeSubTable
- Mark as deprecated columns in PrintGroupSubTable
- Simplify method 'createPrintGroup' in ReceiptApi

2020-09-17 08:51 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/MedicineAttribute.kt
> +        val preferentialMedicineType: PreferentialMedicineType = PreferentialMedicineType.NON_PREFERENTIAL_MEDICINE,
откатить

2020-09-17 08:54 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/MedicineAttribute.kt
> +        @FiscalRequisite(tag = FiscalTags.MEDICINE_ADDITIONAL_REQUISITE_VALUE)
надо как-то описать понятней почему 2 поля мапятся в один тег

2020-09-17 08:57 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/Position.java
> +     * БУдет записано в тэг 1191
опечатка

2020-09-17 08:58 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/PrintGroupSubTable.kt
> +            message = "Будет удалено из PrintGroupSubTable и перенесено в MedicineAttributeSubTable",
допиши дату плз

2020-09-17 09:01 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/ReceiptApi.kt
> +        val oldSubjectId = cursor.optString(MedicineAttributeSubTable.COLUMN_SUBJECT_ID)
не та колонка/таблица

2020-09-17 09:09 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/PrintGroupSubTable.kt
> +            message = "Будет удалено из PrintGroupSubTable и перенесено в MedicineAttributeSubTable",
давай удалим просто

2020-09-17 09:19 UTC, xcam requested changes
См замечания

2020-09-17 16:41 UTC, Affordall commented on src/main/java/ru/evotor/framework/receipt/MedicineAttribute.kt
> +        val preferentialMedicineType: PreferentialMedicineType = PreferentialMedicineType.NON_PREFERENTIAL_MEDICINE,
Done

2020-09-17 16:45 UTC, Affordall commented on src/main/java/ru/evotor/framework/receipt/MedicineAttribute.kt
> +        @FiscalRequisite(tag = FiscalTags.MEDICINE_ADDITIONAL_REQUISITE_VALUE)
+

2020-09-17 16:47 UTC, Affordall commented on src/main/java/ru/evotor/framework/receipt/Position.java
> +     * БУдет записано в тэг 1191
исправил

2020-09-17 16:48 UTC, Affordall commented on src/main/java/ru/evotor/framework/receipt/PrintGroupSubTable.kt
> +            message = "Будет удалено из PrintGroupSubTable и перенесено в MedicineAttributeSubTable",
удалил

2020-09-17 16:48 UTC, Affordall commented on src/main/java/ru/evotor/framework/receipt/ReceiptApi.kt
> +        val oldSubjectId = cursor.optString(MedicineAttributeSubTable.COLUMN_SUBJECT_ID)
удалил

2020-09-18 10:17 UTC, xcam approved these changes

2020-09-18 10:17 UTC, merged