MRK-166
evotor/integration-library pull request #329
Opened 2020-09-23 11:26 UTC by Affordall

Add fiscal tags
Add default value to PreferentialMedicineType
Add MedicineAttributeSubTable
Mark as deprecated columns in PrintGroupSubTable
Simplify method 'createPrintGroup' in ReceiptApi

2020-09-24 09:30 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/ReceiptApi.kt
> +                    PurchaserType.values()[it.toInt() % PurchaserType.values().size]
такие конструкции приводят к непредсказуемому результату - предлагаю поменять

2020-09-24 09:33 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/MedicineAttribute.kt
> +                    else -> null
это в целом неверно. Я за следующую логику обычно. Мы говорим, что поля не удаляются никогда из парсела и поэтому можем сделать так
`
if(version >= 1){
subjectID = parcel.readString()
}
if(version>= 2){
preferentialMedicineType = Utils.safeValueOf(PreferentialMedicineType::class.java, parcel.readString(),
                                        PreferentialMedicineType.NON_PREFERENTIAL_MEDICINE),
                                medicineAdditionalDetails = parcel.readParcelable(MedicineAdditionalDetails::class.java.classLoader)
}
ну и тд
`

2020-09-24 09:35 UTC, xcam requested changes
см замечания

2020-09-24 13:32 UTC, Affordall commented on src/main/java/ru/evotor/framework/receipt/MedicineAttribute.kt
> +                    else -> null
агась

2020-09-24 13:42 UTC, Affordall commented on src/main/java/ru/evotor/framework/receipt/ReceiptApi.kt
> +                    PurchaserType.values()[it.toInt() % PurchaserType.values().size]
исправил

2020-10-01 09:33 UTC, xcam approved these changes

2020-10-01 09:33 UTC, merged