STDEV-6248 Дать возможность получать данные об дате активации ФН чере…
evotor/integration-library pull request #337
Opened 2020-10-05 11:45 UTC by xcam

…з апи терминала

2020-10-05 11:52 UTC, Affordall requested changes

2020-10-05 11:52 UTC, Affordall commented on src/main/java/ru/evotor/framework/kkt/api/KktApi.kt
> +     * или попытка завершилась неудачей
Может стоит добавить в комментарии кейс с 'еще не активированным ФНом / кассой'?

2020-10-05 16:09 UTC, xcam commented on src/main/java/ru/evotor/framework/kkt/api/KktApi.kt
> +     * или попытка завершилась неудачей
поправил

2020-10-05 16:10 UTC, Affordall approved these changes, later dismissed
lgtm

2020-12-10 08:40 UTC, Affordall approved these changes
lgtm

2020-12-10 08:43 UTC, merged