Stdev 5035
evotor/integration-library pull request #361
Opened 2021-02-26 14:00 UTC by castasat

added cashierPosition

2021-03-02 16:24 UTC, xcam commented on src/main/java/ru/evotor/framework/users/User.kt
> +    var cashierPosition: String? = null
думаю тут стоит назвать просто position? В целом это пользователь - он может быть не только кассиром

2021-03-02 16:25 UTC, xcam commented on src/main/java/ru/evotor/framework/users/User.kt
> +    constructor(uuid: String,
давай внесем inn и position в основной конструктор и сделаем их val
А старый конструктор сделаем неосновным и помеченным deprecated

2021-03-02 16:27 UTC, xcam commented on src/main/java/ru/evotor/framework/users/UserQuery.kt
> +    val cashierPosition = addFieldFilter<String?>(UsersTable.ROW_USER_CASHIER_POSITION)
просто position

2021-03-02 16:27 UTC, xcam commented on src/main/java/ru/evotor/framework/users/UserQuery.kt
> +    val cashierPosition = addFieldFilter<String?>(UsersTable.ROW_USER_CASHIER_POSITION)
давай inn заодно добавим

2021-03-02 16:28 UTC, xcam commented on src/main/java/ru/evotor/framework/users/UserQuery.kt
> +        val cashierPosition = addFieldSorter(UsersTable.ROW_USER_CASHIER_POSITION)
просто position

2021-03-02 16:28 UTC, xcam commented on src/main/java/ru/evotor/framework/users/UserQuery.kt
> +        @JvmField
давай inn добавим еще

2021-03-02 16:29 UTC, xcam commented on src/main/java/ru/evotor/framework/users/UsersTable.kt
> +    const val ROW_USER_CASHIER_POSITION = "USER_CASHIER_POSITION"
просто position? 
и inn еще добавим

2021-03-02 16:29 UTC, xcam requested changes
см комментарии

2021-03-03 13:18 UTC, castasat commented on src/main/java/ru/evotor/framework/users/User.kt
> +    constructor(uuid: String,
+

2021-03-03 13:18 UTC, castasat commented on src/main/java/ru/evotor/framework/users/User.kt
> +    constructor(uuid: String,
есть

2021-03-03 13:26 UTC, castasat commented on src/main/java/ru/evotor/framework/users/User.kt
> +    var cashierPosition: String? = null
есть

2021-03-03 13:41 UTC, castasat commented on src/main/java/ru/evotor/framework/users/UserQuery.kt
> +    val cashierPosition = addFieldFilter<String?>(UsersTable.ROW_USER_CASHIER_POSITION)
есть

2021-03-03 13:43 UTC, castasat commented on src/main/java/ru/evotor/framework/users/UserQuery.kt
> +    val cashierPosition = addFieldFilter<String?>(UsersTable.ROW_USER_CASHIER_POSITION)
Он уже есть выше на 18-й строке

2021-03-03 13:43 UTC, castasat commented on src/main/java/ru/evotor/framework/users/UserQuery.kt
> +        val cashierPosition = addFieldSorter(UsersTable.ROW_USER_CASHIER_POSITION)
есть

2021-03-03 13:44 UTC, castasat commented on src/main/java/ru/evotor/framework/users/UserQuery.kt
> +        @JvmField
Он уже есть выше на 42-й строке

2021-03-03 13:53 UTC, castasat commented on src/main/java/ru/evotor/framework/users/UsersTable.kt
> +    const val ROW_USER_CASHIER_POSITION = "USER_CASHIER_POSITION"
Поправил, inn уже есть выше на 12-й строке

2021-03-04 07:54 UTC, xcam submitted a review, later dismissed

2021-03-04 08:11 UTC, xcam approved these changes

2021-03-04 08:12 UTC, merged