STDEV-6963
evotor/integration-library pull request #362
Opened 2021-03-01 11:23 UTC by Affordall

- add new fields in Position for partial sale

2021-04-07 10:25 UTC, xcam commented on src/main/java/ru/evotor/framework/CursorExt.kt
> +internal fun Cursor.safeGetString(columnIndex: Int): String? {
курсор вроде нормально поддерживает получение null строки если колонка точно есть. Кажется этот метод лишний

2021-04-07 10:29 UTC, xcam commented on src/main/java/ru/evotor/framework/KotlinUtils.kt
> +        ReplaceWith(expression = "Utils.safeValueOf(T::class.java, type, default)", imports = ["ru.evotor.framework.Utils"]),
кажется что Utils тоже не должен быть публичным )

2021-04-07 10:29 UTC, xcam commented on src/main/java/ru/evotor/framework/KotlinUtils.kt
> +@Deprecated("Это внутренний метод. Он не должен быть публичным", level = DeprecationLevel.ERROR)
может тогда сделать internal просто?

2021-04-07 10:31 UTC, xcam commented on src/main/java/ru/evotor/framework/FormatExt.kt
> +internal fun Long.formatPrice(): BigDecimal {
это тогда money, а не price. Потому как используется и для суммы

2021-04-07 10:32 UTC, xcam commented on src/main/java/ru/evotor/framework/FormatExt.kt
> +package ru.evotor.framework
может тогда у cursor расширить методами getQuantity(index:Int)?

2021-04-07 10:33 UTC, xcam commented on src/main/java/ru/evotor/framework/KotlinUtils.kt
> +        ReplaceWith(expression = "safeGetLong(columnIndex)", imports = ["ru.evotor.framework.CursorExt"]),
так он жеж internal

2021-04-07 10:36 UTC, xcam commented on src/main/java/ru/evotor/framework/core/action/datamapper/BundleExt.kt
> +    } catch (e: NumberFormatException) {
мож залогировать?

2021-04-07 10:43 UTC, xcam commented on src/main/java/ru/evotor/framework/core/action/datamapper/BundleExt.kt
> +fun Bundle.optBigDecimal(key: String, default: BigDecimal? = null): BigDecimal? {
Чет по default надо поговорить видимо. У меня тут не склеивается

2021-04-07 10:44 UTC, xcam commented on src/main/java/ru/evotor/framework/core/action/datamapper/PositionMapper.java
> +        Partial partial = Partial.Companion.from(bundle.getBundle(KEY_PARTIAL_SALE));
@JVMStatic можно добавить. Тогда Companion не надо будет писать

2021-04-07 10:46 UTC, xcam commented on src/main/java/ru/evotor/framework/inventory/InventoryApi.kt
> +                                        alcoholByVolume = cursor.safeGetLong(ProductTable.ROW_ALCOHOL_BY_VOLUME)?.formatQuantity(),
вообще это не количество

2021-04-07 10:49 UTC, xcam commented on src/main/java/ru/evotor/framework/inventory/ProductItem.kt
> +    enum class PartialSaleFrequency {
AllowPartialSell? Вроде так договорились?

2021-04-07 10:51 UTC, xcam commented on src/main/java/ru/evotor/framework/mapper/FiscalDocumentMapper.kt
> +import ru.evotor.framework.safeGetLong
чет мне optLong больше нравился

2021-04-07 10:53 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/position/Partial.kt
> +data class Partial(
Плохо называть классы прилагательными
+ это не совпадает с комментарием

2021-04-07 10:55 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/position/Partial.kt
> +        val initialQuantity: BigDecimal,
непонятно зачем это поле.

2021-04-07 10:56 UTC, xcam requested changes
нужны доработки

2021-04-07 15:45 UTC, Affordall commented on src/main/java/ru/evotor/framework/CursorExt.kt
> +internal fun Cursor.safeGetString(columnIndex: Int): String? {
Обсудили, оставляем

2021-04-07 15:50 UTC, Affordall commented on src/main/java/ru/evotor/framework/KotlinUtils.kt
> +        ReplaceWith(expression = "Utils.safeValueOf(T::class.java, type, default)", imports = ["ru.evotor.framework.Utils"]),
Исправил

2021-04-07 15:50 UTC, Affordall commented on src/main/java/ru/evotor/framework/KotlinUtils.kt
> +@Deprecated("Это внутренний метод. Он не должен быть публичным", level = DeprecationLevel.ERROR)
убрали

2021-04-07 15:51 UTC, Affordall commented on src/main/java/ru/evotor/framework/FormatExt.kt
> +internal fun Long.formatPrice(): BigDecimal {
Согласен

2021-04-07 15:52 UTC, Affordall commented on src/main/java/ru/evotor/framework/KotlinUtils.kt
> +        ReplaceWith(expression = "safeGetLong(columnIndex)", imports = ["ru.evotor.framework.CursorExt"]),
убрали

2021-04-07 15:53 UTC, Affordall commented on src/main/java/ru/evotor/framework/core/action/datamapper/BundleExt.kt
> +    } catch (e: NumberFormatException) {
изменил

2021-04-08 13:05 UTC, Affordall commented on src/main/java/ru/evotor/framework/core/action/datamapper/BundleExt.kt
> +fun Bundle.optBigDecimal(key: String, default: BigDecimal? = null): BigDecimal? {
Убрал default

2021-04-08 13:09 UTC, Affordall commented on src/main/java/ru/evotor/framework/core/action/datamapper/PositionMapper.java
> +        Partial partial = Partial.Companion.from(bundle.getBundle(KEY_PARTIAL_SALE));
Ага, убрал

2021-04-08 13:10 UTC, Affordall commented on src/main/java/ru/evotor/framework/inventory/InventoryApi.kt
> +                                        alcoholByVolume = cursor.safeGetLong(ProductTable.ROW_ALCOHOL_BY_VOLUME)?.formatQuantity(),
добавил еще один метод для volume

2021-04-08 13:10 UTC, Affordall commented on src/main/java/ru/evotor/framework/mapper/FiscalDocumentMapper.kt
> +import ru.evotor.framework.safeGetLong
Обсудили, оставим так, для единообразия

2021-04-08 13:10 UTC, Affordall commented on src/main/java/ru/evotor/framework/receipt/position/Partial.kt
> +data class Partial(
Исправил

2021-04-08 13:10 UTC, Affordall commented on src/main/java/ru/evotor/framework/receipt/position/Partial.kt
> +        val initialQuantity: BigDecimal,
Ага, обсудили, убрал

2021-04-08 13:16 UTC, Affordall commented on src/main/java/ru/evotor/framework/inventory/ProductItem.kt
> +    enum class PartialSaleFrequency {
исправил на AllowPartialRealization

2021-04-08 14:55 UTC, Affordall commented on src/main/java/ru/evotor/framework/FormatExt.kt
> +package ru.evotor.framework
Ага, так и сделал

2021-04-08 15:05 UTC, Affordall commented on src/main/java/ru/evotor/framework/CursorExt.kt
> +internal fun Cursor.safeGetString(columnIndex: Int): String? {
Переименовал

2021-04-13 06:24 UTC, xcam commented on src/main/java/ru/evotor/framework/core/action/datamapper/PositionMapper.java
> +    private static final String KEY_PARTIAL_REALISATION = "partialRealisation";
в одном месте realiZation в другом realiSation - нужно привести к одному варианту

2021-04-13 06:31 UTC, xcam commented on src/main/java/ru/evotor/framework/kkt/api/KktApi.kt
> +            context: Context,
кажется поехало форматирование?

2021-04-13 06:32 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/Position.java
> +        // Partial sale
realization?

2021-04-13 06:33 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/Position.java
> +     * - альтернативный табак {@link ProductType#TOBACCO_PRODUCTS_MARKED}
может тогда именно эти методы модифицировать (toTabaccoMarked и тд) и не давать setPartial напрямую?

2021-04-13 06:34 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/Position.java
> +        public Builder setPartialRealization(@Nullable PartialRealization partialRealization) {
думаю стоит оставить либо setPartial либо toPartial - 2 метода не нужны?

2021-04-13 06:36 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/ReceiptApi.kt
> +                Uri.withAppendedPath(PositionTable.URI, barcode),
поехало форматирование

2021-04-13 06:37 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/position/mapper/PositionPartialMapper.kt
> +internal object PositionPartialMapper {
PartialRealizationMapper?

2021-04-13 06:38 UTC, xcam requested changes
см комменты

2021-04-13 15:11 UTC, Affordall commented on src/main/java/ru/evotor/framework/core/action/datamapper/PositionMapper.java
> +    private static final String KEY_PARTIAL_REALISATION = "partialRealisation";
Z будет

2021-04-13 15:12 UTC, Affordall commented on src/main/java/ru/evotor/framework/kkt/api/KktApi.kt
> +            context: Context,
Не правил этот метод, авто-форматирование не правит ничего

2021-04-13 15:22 UTC, Affordall commented on src/main/java/ru/evotor/framework/receipt/Position.java
> +        // Partial sale
ага

2021-04-13 15:23 UTC, Affordall commented on src/main/java/ru/evotor/framework/receipt/position/mapper/PositionPartialMapper.kt
> +internal object PositionPartialMapper {
да

2021-04-13 16:17 UTC, Affordall commented on src/main/java/ru/evotor/framework/core/action/datamapper/PositionMapper.java
> +    private static final String KEY_PARTIAL_REALISATION = "partialRealisation";
привел

2021-04-14 09:27 UTC, Affordall commented on src/main/java/ru/evotor/framework/receipt/Position.java
> +        public Builder setPartialRealization(@Nullable PartialRealization partialRealization) {
ты прав, оптимизировал

2021-04-14 09:29 UTC, Affordall commented on src/main/java/ru/evotor/framework/receipt/Position.java
> +     * - альтернативный табак {@link ProductType#TOBACCO_PRODUCTS_MARKED}
тогда мы потеряем гибкость

2021-05-26 08:07 UTC, Affordall commented on src/main/java/ru/evotor/framework/receipt/ReceiptApi.kt
> +                Uri.withAppendedPath(PositionTable.URI, barcode),
исправилось

2021-05-26 09:34 UTC, xcam approved these changes

2021-05-26 09:34 UTC, merged