STDEV-7843
evotor/integration-library pull request #364
Opened 2021-03-13 14:14 UTC by apliter

Добавлены новые команды для открытия чека коррекции под ФФД >= 1.1
Добавлены новые типы чеков и SettlementType.kt
Deprecated методы KktApi.kt

2021-03-15 08:26 UTC, xcam commented on src/main/java/ru/evotor/framework/core/action/command/open_receipt_command/OpenCorrectionIncomeReceiptCommand.kt
> +    fun getChanges(): List<PositionAdd> = this.changes
почему просто поля не сделать public?

2021-03-15 08:28 UTC, xcam commented on src/main/java/ru/evotor/framework/kkt/api/KktApi.kt
> +            replaceWith = ReplaceWith("OpenCorrectionIncomeReceiptCommand \nOpenCorrectionOutcomeReceiptCommand")
Здесь вроде больше подходит PrintSellReceiptCommand

2021-03-15 08:28 UTC, xcam requested changes
см замечания

2021-03-15 08:36 UTC, apliter commented on src/main/java/ru/evotor/framework/core/action/command/open_receipt_command/OpenCorrectionIncomeReceiptCommand.kt
> +    fun getChanges(): List<PositionAdd> = this.changes
+

2021-03-15 08:39 UTC, apliter commented on src/main/java/ru/evotor/framework/kkt/api/KktApi.kt
> +            replaceWith = ReplaceWith("OpenCorrectionIncomeReceiptCommand \nOpenCorrectionOutcomeReceiptCommand")
Задача требует обычного цикла жизни чека в POS-е. Поэтому использую именно Open* команды. 
Можно в догрузку еще и Print* команды сделать, или расширить имеющиеся Sell\Payback команды.

2021-03-17 11:25 UTC, apliter commented on src/main/java/ru/evotor/framework/kkt/api/KktApi.kt
> +            replaceWith = ReplaceWith("OpenCorrectionIncomeReceiptCommand \nOpenCorrectionOutcomeReceiptCommand")
+

2021-04-14 04:47 UTC, xcam commented on src/main/java/ru/evotor/framework/core/action/command/open_receipt_command/OpenCorrectionIncomeReceiptCommand.kt
> + * @param correctionDate Дата совершения корректируемого расчета (ТЕГ 1178)
для ТЕГ 1178 у нас есть специальный класс: FiscalTag. Предлагаю использовать его

2021-04-14 04:48 UTC, xcam commented on src/main/java/ru/evotor/framework/core/action/command/open_receipt_command/OpenCorrectionIncomeReceiptCommand.kt
> + * @param correctionType Тип коррекции BY_SELF - самостоятельная операция, BY_PRESCRIBED - операция по предписанию налогового органа  (ТЕГ 1173)
тут не надо расписывать возможные значения. Иначе при добавлении значения в enum 100% что сюда забудем добавить

2021-04-14 04:56 UTC, xcam commented on src/main/java/ru/evotor/framework/kkt/api/KktApi.kt
> +    @Deprecated(
я вот думаю не стоит ли под капотом в эвопосе сделать поддержку этого метода и для 1.1?
Мы в теории можем формировать чек коррекции с 1 позицией на всю сумму коррекции и 1 стандартной оплатой

2021-04-14 04:57 UTC, xcam commented on src/main/java/ru/evotor/framework/core/action/command/print_receipt_command/PrintCorrectionOutcomeReceiptCommand.kt
> +class PrintCorrectionOutcomeReceiptCommand(
этот метод будет работать с ФФД 1.05?

2021-04-14 04:59 UTC, xcam requested changes
См комментарии

2021-04-14 10:23 UTC, apliter commented on src/main/java/ru/evotor/framework/core/action/command/open_receipt_command/OpenCorrectionIncomeReceiptCommand.kt
> + * @param correctionDate Дата совершения корректируемого расчета (ТЕГ 1178)
+

2021-04-14 10:23 UTC, apliter commented on src/main/java/ru/evotor/framework/core/action/command/open_receipt_command/OpenCorrectionIncomeReceiptCommand.kt
> + * @param correctionType Тип коррекции BY_SELF - самостоятельная операция, BY_PRESCRIBED - операция по предписанию налогового органа  (ТЕГ 1173)
+

2021-05-11 15:10 UTC, apliter commented on src/main/java/ru/evotor/framework/core/action/command/print_receipt_command/PrintCorrectionOutcomeReceiptCommand.kt
> +class PrintCorrectionOutcomeReceiptCommand(
В теории - да

2021-05-24 11:43 UTC, apliter commented on src/main/java/ru/evotor/framework/kkt/api/KktApi.kt
> +    @Deprecated(
Да, сделано почти так. 
Методы kktApi будут вызывать print* команду.

2021-05-24 11:43 UTC, apliter commented on src/main/java/ru/evotor/framework/core/action/command/print_receipt_command/PrintCorrectionOutcomeReceiptCommand.kt
> +class PrintCorrectionOutcomeReceiptCommand(
Только если будет передана одна позиция. Больше одной - ошибка в callback-е

2021-05-24 14:19 UTC, xcam approved these changes

2021-05-24 16:06 UTC, apliter commented
переезжаем в https://github.com/evotor/integration-library/pull/371

2021-05-24 16:06 UTC, closed without merging