Stdev 15279
evotor/integration-library pull request #476
Opened 2023-05-29 06:40 UTC by TOvchinnikova

2023-06-19 14:32 UTC, Affordall requested changes

2023-06-19 14:32 UTC, Affordall commented on src/main/java/ru/evotor/framework/inventory/ProductType.java
> +    BEER_MARKED_KEG
Еще нужно повысить версию библиотеки "def version", т.к. в POS нужно будет обрабатывать обратную совместимость при мерже интеграций

https://github.com/evotor/integration-library/blob/develop/build.gradle

2023-06-20 03:04 UTC, TOvchinnikova commented on src/main/java/ru/evotor/framework/inventory/ProductType.java
> +    BEER_MARKED_KEG
Спасибо) Повысила)

2023-06-20 07:48 UTC, Affordall approved these changes

2023-06-20 07:48 UTC, merged