STDEV-14924
evotor/integration-library pull request #485
Opened 2023-07-07 05:34 UTC by vadimka1206

2023-07-11 08:02 UTC, Affordall submitted a review, later dismissed
LGTM

2023-07-11 08:27 UTC, xcam commented on src/main/java/ru/evotor/framework/core/action/command/close_bank_session/CloseBankSessionCommand.kt
> + * Команда закрытия смены патежного терминала
опечатка в слове пЛатежного

2023-07-11 08:28 UTC, xcam commented on src/main/java/ru/evotor/framework/core/action/command/close_bank_session/CloseBankSessionCommand.kt
> + * @param userUuid - Идентификатор сотрудника в формате `uuid4`, от лица которого будет произведена операция. Если передано null, то будет выбран текущий авторизованный сотрудник. @see ru.evotor.fram
этот параметр тут кажется не нужен - мы его разве как-то используем?

2023-07-11 08:31 UTC, xcam commented on src/main/java/ru/evotor/framework/core/action/command/close_bank_session/CloseBankSessionCommandResult.kt
> +        const val ERROR_CODE_FFD_12_FRAUD_DETECTED = -1
этот код ошибки выглядит инородным. Он точно нужен?

2023-07-11 08:32 UTC, xcam commented on src/main/java/ru/evotor/framework/core/action/command/close_bank_session/CloseBankSessionCommand.kt
> +class CloseBankSessionCommand(
будет ли распечатан результат или нужно самому допечатать слип?

2023-07-11 08:32 UTC, xcam requested changes
См комментарии

2023-07-11 08:54 UTC, vadimka1206 commented on src/main/java/ru/evotor/framework/core/action/command/close_bank_session/CloseBankSessionCommand.kt
> +class CloseBankSessionCommand(
Решили, что допечатывать нужно будет самим

2023-07-11 09:07 UTC, vadimka1206 commented on src/main/java/ru/evotor/framework/core/action/command/close_bank_session/CloseBankSessionCommand.kt
> + * Команда закрытия смены патежного терминала
Исправил

2023-07-11 09:10 UTC, vadimka1206 commented on src/main/java/ru/evotor/framework/core/action/command/close_bank_session/CloseBankSessionCommand.kt
> + * @param userUuid - Идентификатор сотрудника в формате `uuid4`, от лица которого будет произведена операция. Если передано null, то будет выбран текущий авторизованный сотрудник. @see ru.evotor.fram
Мы его используем только для проверки пользователя, дальше он не нужен. Сделано согласно спецификации
https://confluence.evotor.ru/pages/viewpage.action?pageId=92782209

2023-07-11 16:46 UTC, vadimka1206 commented on src/main/java/ru/evotor/framework/core/action/command/close_bank_session/CloseBankSessionCommandResult.kt
> +        const val ERROR_CODE_FFD_12_FRAUD_DETECTED = -1
Обсудили с Олегом, да, эта проверка тут не нужна, удалил

2023-07-12 06:04 UTC, vadimka1206 commented on src/main/java/ru/evotor/framework/core/action/command/close_bank_session/CloseBankSessionCommand.kt
> + * @param userUuid - Идентификатор сотрудника в формате `uuid4`, от лица которого будет произведена операция. Если передано null, то будет выбран текущий авторизованный сотрудник. @see ru.evotor.fram
Обсудили с Олегом, userUuid нужен для логирования в logDB, это будет добавлено позже отдельным запросом

2023-07-17 07:45 UTC, xcam commented on src/main/java/ru/evotor/framework/core/action/command/close_bank_session/CloseBankSessionCommandResult.kt
> +        const val ERROR_CODE_NO_AUTHENTICATED_USER = -2
получается, что если пользователь не передан и не залогинен, то мы не делаем сверку итогов?
Мне кажется, что для сверки итогов пользователь все таки не нужен. Если скажете что нужен, то ок

2023-07-17 07:46 UTC, xcam requested changes
см комменты

2023-08-03 14:16 UTC, xcam approved these changes

2023-08-14 07:20 UTC, merged