STDEV-17516
evotor/integration-library pull request #502
Opened 2024-01-09 06:43 UTC by vadimka1206

2024-01-09 08:08 UTC, xcam commented on src/main/java/ru/evotor/framework/core/action/command/trigger_receipt_discount_event_command/TriggerReceiptDiscountEventCommandResult.kt
> +        const val ERROR_CODE_KKM_IS_BUSY = -1
этот код лишний?

2024-01-09 08:08 UTC, xcam commented on src/main/java/ru/evotor/framework/core/action/command/trigger_receipt_discount_event_command/TriggerReceiptDiscountEventCommandResult.kt
> +        const val ERROR_CODE_NO_AUTHENTICATED_USER = -2
этот код лишний?

2024-01-09 08:09 UTC, xcam commented on src/main/java/ru/evotor/framework/core/action/command/trigger_receipt_discount_event_command/TriggerReceiptDiscountEventCommandResult.kt
> +    }
нужен ли отдельный код ошибки для случая когда к чеку невозможно применить эту скидку. Например, если это возврат на основании и в чеке продажи не было скидок вообще

2024-01-09 08:11 UTC, xcam commented on src/main/java/ru/evotor/framework/core/action/command/trigger_receipt_discount_event_command/TriggerReceiptDiscountEventCommandResult.kt
> +        return Bundle()
не совсем понятно к какому чеку в итоге применилось событие. Мне кажется нужно либо делать события под каждый тип чека, либо возвращать тут какой-то признак чека, например uuid

2024-01-09 08:12 UTC, xcam requested changes
см комментарии

2024-01-09 08:20 UTC, vadimka1206 commented on src/main/java/ru/evotor/framework/core/action/command/trigger_receipt_discount_event_command/TriggerReceiptDiscountEventCommandResult.kt
> +        const val ERROR_CODE_KKM_IS_BUSY = -1
Нет, эту ошибку мы отправляем из поса, если у нас непустой action

2024-01-09 08:21 UTC, vadimka1206 commented on src/main/java/ru/evotor/framework/core/action/command/trigger_receipt_discount_event_command/TriggerReceiptDiscountEventCommandResult.kt
> +        const val ERROR_CODE_NO_AUTHENTICATED_USER = -2
Мы уже в какой-то предыдущей задаче обсуждали то же самое, и пришли к тому, что должна быть стандартная проверка на пользователя. Олег говорил про возможное логирование, которое мы захотим добавить

2024-01-11 16:40 UTC, vadimka1206 commented on src/main/java/ru/evotor/framework/core/action/command/trigger_receipt_discount_event_command/TriggerReceiptDiscountEventCommandResult.kt
> +        return Bundle()
Перенес в SellApi, BuyApi, PaybackApi

2024-01-16 07:19 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/formation/event/TriggerReceiptDiscountEventRequestedEvent.kt
> +        const val NAME = "evo.v2.receipt.triggerReceiptDiscountEventCommand"
не нашел где это используется

2024-01-16 07:20 UTC, xcam requested changes
небольшое вопрос

2024-01-16 07:24 UTC, vadimka1206 commented on src/main/java/ru/evotor/framework/receipt/formation/event/TriggerReceiptDiscountEventRequestedEvent.kt
> +        const val NAME = "evo.v2.receipt.triggerReceiptDiscountEventCommand"
Да, забыл удалить, исправил

2024-01-18 07:23 UTC, xcam approved these changes

2024-01-26 10:22 UTC, merged