Stdev 19980
evotor/integration-library pull request #540
Opened 2024-09-30 16:36 UTC by vadimka1206

2024-10-02 13:17 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/position/SaleBanTime.kt
> +        fun parseHoursAndMinutes(time: String): Pair<Int, Int> {
private?

2024-10-02 13:17 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/position/SaleBanTime.kt
> +            if (time.matches(Regex("""\d{2}:\d{2}"""))) {
создание Regex вроде не очень быстрое занятие. Может закешировать его?

2024-10-02 13:55 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/position/SaleBanTime.kt
> +    val startTime: String,
тут бы не помешал javadoc.
Нужен формат в котором можно задавать время

2024-10-02 13:58 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/position/SaleBanTime.kt
> +data class SaleBanTime(
предлагаю переименовать в TimeRange и перенести в другой package. Возможно такой класс где-то еще понадобится. Вдруг мы захотим контролировать время начисления скидки

2024-10-02 13:59 UTC, xcam commented on src/main/java/ru/evotor/framework/receipt/Position.java
> +     * Признак времени запрета продажи
а тут время когда можно продавать или нельзя?

2024-10-02 13:59 UTC, xcam requested changes
см комментарии

2024-10-03 14:56 UTC, vadimka1206 commented on src/main/java/ru/evotor/framework/receipt/Position.java
> +     * Признак времени запрета продажи
Когда нельзя

2024-10-03 15:02 UTC, vadimka1206 commented on src/main/java/ru/evotor/framework/receipt/position/SaleBanTime.kt
> +data class SaleBanTime(
Согласен, класс переименовал, но вот не совсем уверен, в какой package положить. Сейчас перенес в ru.evotor.framework.receipt, думаю, эта сущность нам нужна будет в любом случае в контексте чека

2024-10-03 15:04 UTC, vadimka1206 commented on src/main/java/ru/evotor/framework/receipt/position/SaleBanTime.kt
> +    val startTime: String,
Добавил

2024-10-03 15:05 UTC, vadimka1206 commented on src/main/java/ru/evotor/framework/receipt/position/SaleBanTime.kt
> +            if (time.matches(Regex("""\d{2}:\d{2}"""))) {
Ага, не подумал об этом, изменил

2024-10-03 15:06 UTC, vadimka1206 commented on src/main/java/ru/evotor/framework/receipt/position/SaleBanTime.kt
> +        fun parseHoursAndMinutes(time: String): Pair<Int, Int> {
Метод использовался в ПОСе, так как мы оперировали именно строками, но раз мы теперь храним численные значения, то да, можно заприватить

2024-10-08 14:38 UTC, xcam approved these changes

2024-10-08 14:38 UTC, merged