STDEV-15045
evotor/integration-library pull request #544
Opened 2024-10-28 15:37 UTC by vadimka1206

2024-10-30 13:41 UTC, xcam commented on src/main/java/ru/evotor/framework/payment/CashlessInfo.kt
> +            val method = if (methodOrdinal == -1 || methodOrdinal >= Method.values().size) {
предлагаю поменять methodOrdinal == -1 на methodOrdinal < 0

2024-10-30 13:45 UTC, xcam commented on src/main/java/ru/evotor/framework/payment/CashlessInfo.kt
> +        UNKNOWN
тут видится проблема. В будущем, когда этот енам будет расширятся новыми значениями, появится соблазн добавить значение в середину, перед UNKNOWN. Это может привести к тому, что при передаче через ordinal у нас будут получаться  не те значения. Я вижу следующие возможные решения

- поставить UNKOWN в начало - перед QR
- перейти при записи в bundle от ordinal к enum.name. Главное не забыть proguard-consumer доработать
- Написать коммент, что добавление возможно только в конец enum

2024-10-30 13:47 UTC, xcam commented on src/main/java/ru/evotor/framework/payment/CashlessInfo.kt
> +                uuid = bundle.getString(KEY_UUID) ?: throw IllegalArgumentException("uuid should not be null"),
стоит ли это выкидывания исключения? Может просто вернуть null?

Иначе сейчас из-за ошибки формирования CashlessInfo мы можем потерять результат оплаты

2024-10-30 13:48 UTC, xcam commented on src/main/java/ru/evotor/framework/core/action/datamapper/PaymentMapper.java
> +import ru.evotor.framework.payment.CashlessInfo;
а у нас не было еще таблицы или контент провайдера, который бы возвращал данные по оплатам?

2024-10-30 13:48 UTC, xcam requested changes
см комментарии

2024-10-31 11:07 UTC, vadimka1206 commented on src/main/java/ru/evotor/framework/payment/CashlessInfo.kt
> +            val method = if (methodOrdinal == -1 || methodOrdinal >= Method.values().size) {
Done

2024-10-31 11:08 UTC, vadimka1206 commented on src/main/java/ru/evotor/framework/payment/CashlessInfo.kt
> +        UNKNOWN
Согласен, перенес unknown в начало и добавил еще коммент на всякий случай

2024-10-31 11:09 UTC, vadimka1206 commented on src/main/java/ru/evotor/framework/payment/CashlessInfo.kt
> +                uuid = bundle.getString(KEY_UUID) ?: throw IllegalArgumentException("uuid should not be null"),
Наверное, ты прав, поменял на null

2024-10-31 11:09 UTC, vadimka1206 commented on src/main/java/ru/evotor/framework/core/action/datamapper/PaymentMapper.java
> +import ru.evotor.framework.payment.CashlessInfo;
Точно, забыл про него, доработал ReceiptApi

2024-11-05 15:06 UTC, xcam approved these changes

2024-11-05 15:06 UTC, merged